"""The hugo step: build a Hugo site in <out>/site-hugo/ from the
converted archive. Same reproducibility contract as the myst step (see
sites.py); render with `hugo` or `hugo server` inside <out>/site-hugo/
(https://gohugo.io).

Each post becomes a Hugo leaf bundle, content/posts/<stem>/index.md with
its images beside it, so the bundle directory name is the page URL
(/posts/<stem>/). Front matter is JSON (Hugo reads it natively): tags and
authors feed Hugo's taxonomies, which give the tag/author listing pages
and per-term RSS feeds, and every old inbound path (Medium slug+id,
/p/<id>, Ghost-era) becomes an alias, so Hugo emits redirect stubs for
old links on any static host. Hugo has no default theme, so the exporter
writes a small self-contained one (layouts/ + css); replace it with any
theme without touching content/. Search is the one feature Hugo does not
generate: run `pagefind --site public` after `hugo` for a static search
UI.
"""

import json
import sys

from .sites import (clean_site, export_content, load_site_inputs, old_paths,
                    page_stems, write_redirects_csv)

CONFIG = """\
# Generated by `medium-archive hugo`; do not edit.
# Site title/description/intro come from <out>/site.json.
baseURL = {base_url}
title = {title}

[taxonomies]
tag = "tags"
author = "authors"

[params]
description = {description}

[markup.goldmark.renderer]
# some old bodies carry fragments of raw HTML; render them
unsafe = true
"""

BASEOF = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ if not .IsHome }}{{ .Title }} · {{ end }}{{ site.Title }}</title>
{{ with or .Description site.Params.description }}<meta name="description" content="{{ . }}">{{ end }}
{{ range .AlternativeOutputFormats }}<link rel="{{ .Rel }}" type="{{ .MediaType.Type }}" href="{{ .Permalink }}" title="{{ site.Title }}">
{{ end }}<link rel="stylesheet" href="{{ "css/style.css" | relURL }}">
</head>
<body>
<header><nav>
<a class="site" href="{{ "/" | relURL }}">{{ site.Title }}</a>
<a href="{{ "/tags/" | relURL }}">Tags</a>
<a href="{{ "/authors/" | relURL }}">Authors</a>
<a href="{{ "/index.xml" | relURL }}">RSS</a>
</nav></header>
<main>
{{ block "main" . }}{{ end }}
</main>
</body>
</html>
"""

HOME = """\
{{ define "main" }}
<h1>{{ site.Title }}</h1>
{{ .Content }}
{{ range site.RegularPages.GroupByDate "2006" }}
<h2>{{ .Key }}</h2>
<ul class="post-list">
{{ range .Pages }}<li><time>{{ .Date.Format "2006-01-02" }}</time> <a href="{{ .RelPermalink }}">{{ .Title }}</a>{{ with .GetTerms "authors" }} · {{ range . }}{{ .LinkTitle }} {{ end }}{{ end }}</li>
{{ end }}</ul>
{{ end }}
{{ end }}
"""

SINGLE = """\
{{ define "main" }}
<article>
<h1>{{ .Title }}</h1>
<p class="meta"><time>{{ .Date.Format "2006-01-02" }}</time>{{ range .GetTerms "authors" }} · <a href="{{ .RelPermalink }}">{{ .LinkTitle }}</a>{{ end }}</p>
{{ .Content }}
{{ with .GetTerms "tags" }}<p class="tags">{{ range . }}<a href="{{ .RelPermalink }}">#{{ .LinkTitle }}</a> {{ end }}</p>{{ end }}
</article>
{{ end }}
"""

LIST = """\
{{ define "main" }}
<h1>{{ .Title }}</h1>
{{ .Content }}
<ul class="post-list">
{{ range .Pages.ByDate.Reverse }}<li><time>{{ .Date.Format "2006-01-02" }}</time> <a href="{{ .RelPermalink }}">{{ .Title }}</a></li>
{{ end }}</ul>
{{ end }}
"""

TERMS = """\
{{ define "main" }}
<h1>{{ .Title }}</h1>
<ul class="term-list">
{{ range .Data.Terms.Alphabetical }}<li><a href="{{ .Page.RelPermalink }}">{{ .Page.Title }}</a> ({{ .Count }})</li>
{{ end }}</ul>
{{ end }}
"""

CSS = """\
body { max-width: 46rem; margin: 0 auto; padding: 0 1rem 4rem;
       font: 1.05rem/1.6 system-ui, sans-serif; color: #222; }
header nav { padding: 1rem 0; border-bottom: 1px solid #ddd; }
header nav a { margin-right: 1rem; color: #555; text-decoration: none; }
header nav a.site { font-weight: 700; color: #222; }
a { color: #0a67a3; }
img { max-width: 100%; height: auto; }
pre { overflow-x: auto; padding: .8rem; background: #f6f6f6; }
code { background: #f6f6f6; }
blockquote { margin-left: 0; padding-left: 1rem; border-left: 3px solid #ddd; color: #555; }
.post-list { list-style: none; padding: 0; }
.post-list time, .meta time { color: #777; font-variant-numeric: tabular-nums; }
.meta, .tags { color: #777; }
figcaption, em img + em { color: #777; }
"""

TEMPLATES = {
    "layouts/_default/baseof.html": BASEOF,
    "layouts/index.html": HOME,
    "layouts/_default/single.html": SINGLE,
    "layouts/_default/list.html": LIST,
    "layouts/_default/taxonomy.html": LIST,
    "layouts/_default/terms.html": TERMS,
    "static/css/style.css": CSS,
}


def front_matter(url: str, post: dict) -> str:
    front = {"title": post["title"]}
    if post.get("date"):
        front["date"] = post["date"]
    if post.get("updated"):
        front["lastmod"] = post["updated"]
    if post.get("description"):
        front["description"] = post["description"]
    if post.get("tags"):
        front["tags"] = post["tags"]
    if post.get("author"):
        front["authors"] = [post["author"]]
    front["aliases"] = [path for path, _ in old_paths(post, url)]
    return json.dumps(front, indent=2, ensure_ascii=False) + "\n\n"


def build_site(out):
    manifest, config = load_site_inputs(out)
    stems = page_stems(manifest)
    site = out / "site-hugo"
    clean_site(site, keep=("public", "resources"))

    (site / "content").mkdir(parents=True)
    (site / "content" / "_index.md").write_text(
        json.dumps({"title": config["title"]}) + "\n\n"
        + (config.get("intro", "") + "\n" if config.get("intro") else ""),
        encoding="utf-8")
    pages = export_content(out, site, manifest, stems, front_matter)
    (site / "hugo.toml").write_text(CONFIG.format(
        base_url=json.dumps(config.get("base_url", "https://example.org/")),
        title=json.dumps(config["title"], ensure_ascii=False),
        description=json.dumps(config.get("description", ""), ensure_ascii=False),
    ), encoding="utf-8")
    for rel, text in TEMPLATES.items():
        path = site / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    write_redirects_csv(site, manifest, stems, lambda stem: f"/posts/{stem}/")
    print(f"hugo done: {pages}/{len(manifest)} pages -> {site}", file=sys.stderr)
    print(f"render it with: cd {site} && hugo server   (or: hugo; then "
          "`pagefind --site public` for search)", file=sys.stderr)
    return site


def cmd_hugo(args):
    build_site(args.out)
