"""The hugo step: build a Hugo site in <out>/site-hugo/ from the
converted archive. Same reproducibility contract as the myst step (see
sites.py); render with `hugo` or `hugo server` inside <out>/site-hugo/
(https://gohugo.io).

Each post becomes a Hugo leaf bundle, content/posts/<stem>/index.md with
its images beside it, so the bundle directory name is the page URL
(/posts/<stem>/). Front matter is JSON (Hugo reads it natively): tags and
authors feed Hugo's taxonomies, which give the tag/author listing pages
and per-term RSS feeds, and every old inbound path (Medium slug+id,
/p/<id>, Ghost-era) becomes an alias, so Hugo emits redirect stubs for
old links on any static host.

Hugo has no default theme. By default the exporter writes a small
self-contained one (layouts/ + css) with light and dark palettes and a
light/dark/system picker in the header (the choice persists per
browser; with none stored, the system scheme decides); search is then
the one feature Hugo does not generate (run `pagefind --site public`
after `hugo` for a static search UI). Or name a real theme in site.json --

    "hugo": {"theme": "dream",
             "theme_repo": "https://github.com/g1eny0ung/hugo-theme-dream",
             "params": {...}}                       # optional overrides

-- and the exporter emits that theme's config instead of its own
layouts; clone the theme into <out>/site-hugo/themes/<name> once
(regeneration preserves themes/). The Dream theme
(https://hugo-theme-dream.g1en.site) gets first-class treatment: each
post's first image becomes its summary-card cover, the /posts archives
page and /search page (Dream's built-in title+description search) are
created, the RSS nav item is enabled, an Authors nav item points at the
author taxonomy, and siteStartYear is derived from the oldest post.
"""

import json
import shutil
import sys

from .sites import (ImagePlacer, bake_cover_thumbnails,  # noqa: F401
                    clean_site, export_content, image_size,
                    load_site_inputs, old_paths, page_stems, pick_cover,
                    write_redirects_csv)

CONFIG = """\
# Generated by `medium-archive hugo`; do not edit.
# Site title/description/intro come from <out>/site.json.
baseURL = {base_url}
title = {title}
defaultContentLanguage = {locale}
locale = {locale}
{theme}
[pagination]
pagerSize = 24

# a feed announces new posts; the site itself is the archive
[services.rss]
limit = 20

[taxonomies]
tag = "tags"
author = "authors"

{params}

[markup.goldmark.renderer]
# some old bodies carry fragments of raw HTML; render them
unsafe = true
"""

# Runs before the stylesheet loads, so a stored choice cannot flash the
# wrong scheme: an explicit light/dark choice pins data-theme on <html>;
# no attribute means prefers-color-scheme decides (see CSS). Plain
# HTML+JS with no {{ }}, so the hugo and pelican templates embed the
# same snippet verbatim.
THEME_INIT = """\
<script>
(function () {
  try {
    var theme = localStorage.getItem("theme");
    if (theme === "light" || theme === "dark")
      document.documentElement.setAttribute("data-theme", theme);
  } catch (e) {}
})();
</script>
"""

# The header's light/system/dark picker (shared with pelican, like
# THEME_INIT). Hidden until its script runs, since without JS a choice
# could not apply anyway; picking "system" clears the stored choice so
# prefers-color-scheme rules again.
THEME_PICKER = """\
<span class="theme-picker" role="group" aria-label="Color scheme" hidden>
<button type="button" data-set-theme="light" title="Light" aria-label="Light"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><circle cx="12" cy="12" r="4.5"/><path d="M12 2.5v3M12 18.5v3M2.5 12h3M18.5 12h3M5.3 5.3l2.1 2.1M16.6 16.6l2.1 2.1M18.7 5.3l-2.1 2.1M7.4 16.6l-2.1 2.1"/></svg></button>
<button type="button" data-set-theme="system" title="System" aria-label="System"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="4.5" width="18" height="12.5" rx="2"/><path d="M9 20.5h6M12 17v3.5"/></svg></button>
<button type="button" data-set-theme="dark" title="Dark" aria-label="Dark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round" aria-hidden="true"><path d="M20 14.5A8.5 8.5 0 1 1 9.5 4a7 7 0 0 0 10.5 10.5z"/></svg></button>
</span>
<script>
(function () {
  var root = document.documentElement;
  var picker = document.querySelector(".theme-picker");
  var buttons = picker.querySelectorAll("button");
  function apply(choice) {
    if (choice === "system") root.removeAttribute("data-theme");
    else root.setAttribute("data-theme", choice);
    try {
      if (choice === "system") localStorage.removeItem("theme");
      else localStorage.setItem("theme", choice);
    } catch (e) {}
    buttons.forEach(function (b) {
      b.setAttribute("aria-pressed", String(b.dataset.setTheme === choice));
    });
  }
  buttons.forEach(function (b) {
    b.addEventListener("click", function () { apply(b.dataset.setTheme); });
  });
  apply(root.getAttribute("data-theme") || "system");
  picker.hidden = false;
})();
</script>
"""

# The tag/author chip indexes' sort control (shared with pelican, like
# THEME_INIT): by name (A-Z, the order the generators emit, so the no-JS
# page reads the same) or by count, most posts first. Hidden until its
# script runs, since without JS the chips could not be reordered anyway;
# the choice persists per browser, like the theme picker's. The wiring
# waits for DOMContentLoaded because the chip list follows the control
# in the page.
TERM_SORT = """\
<p class="term-sort" role="group" aria-label="Sort by" hidden>Sort by
<button type="button" data-sort="name">name</button>
<button type="button" data-sort="count">count</button>
</p>
<script>
(function () {
  function init() {
    var control = document.querySelector(".term-sort");
    var list = document.querySelector(".term-list");
    if (!control || !list) return;
    var buttons = control.querySelectorAll("button");
    var chips = Array.prototype.map.call(
      list.querySelectorAll(".chip"), function (chip) {
        return { el: chip,
                 name: chip.firstChild.textContent.trim().toLowerCase(),
                 count: parseInt(chip.querySelector("span").textContent, 10) || 0 };
      });
    function apply(order) {
      chips.slice().sort(function (a, b) {
        if (order === "count" && a.count !== b.count) return b.count - a.count;
        return a.name.localeCompare(b.name);
      }).forEach(function (c) { list.appendChild(c.el); });
      try {
        if (order === "name") localStorage.removeItem("term-sort");
        else localStorage.setItem("term-sort", order);
      } catch (e) {}
      buttons.forEach(function (b) {
        b.setAttribute("aria-pressed", String(b.dataset.sort === order));
      });
    }
    buttons.forEach(function (b) {
      b.addEventListener("click", function () { apply(b.dataset.sort); });
    });
    var stored = null;
    try { stored = localStorage.getItem("term-sort"); } catch (e) {}
    apply(stored === "count" ? "count" : "name");
    control.hidden = false;
  }
  if (document.readyState === "loading")
    document.addEventListener("DOMContentLoaded", init);
  else init();
})();
</script>
"""

BASEOF = """\
<!DOCTYPE html>
<html lang="{{ site.Language.Lang }}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ if not .IsHome }}{{ .Title }} · {{ end }}{{ site.Title }}</title>
{{ with or .Description site.Params.description }}<meta name="description" content="{{ . }}">{{ end }}
{{ range .AlternativeOutputFormats }}<link rel="{{ .Rel }}" type="{{ .MediaType.Type }}" href="{{ .Permalink }}" title="{{ site.Title }}">
{{ end }}""" + THEME_INIT + """\
<link rel="stylesheet" href="{{ "css/style.css" | relURL }}">
</head>
<body>
<header class="site-header"><div class="wrap bar">
<a class="site-title" href="{{ "/" | relURL }}">{{ with site.Params.avatar }}<img src="{{ . | relURL }}" alt="">{{ end }}{{ site.Title }}</a>
<nav>
<a href="{{ "/" | relURL }}">Blog</a>
<a href="{{ "/tags/" | relURL }}">Tags</a>
<a href="{{ "/authors/" | relURL }}">Authors</a>
<a href="{{ "/archives/" | relURL }}">Archives</a>
<a href="{{ "/search/" | relURL }}">Search</a>
<a href="{{ "/index.xml" | relURL }}">RSS</a>
""" + THEME_PICKER + """\
</nav>
</div></header>
<main class="wrap">
{{ block "main" . }}{{ end }}
</main>
<footer class="wrap site-footer">{{ site.Params.description }}</footer>
</body>
</html>
"""

CARD = """\
<article class="card">
{{- $cover := "" }}{{ with .Params.cover }}{{ $cover = $.Resources.Get . }}{{ end }}
{{- with $cover }}
<a class="card-cover" href="{{ $.RelPermalink }}">
  {{- if and (eq .MediaType.MainType "image") (not (in (slice "gif" "svg") .MediaType.SubType)) -}}
  {{- /* the exporter bakes covers to exactly 640x360 (crop or
         letterbox by aspect -- see sites.make_cover_thumbnail); Fill
         is the fallback when they kept their source size (no Pillow) */ -}}
  {{- $thumb := . -}}
  {{- if or (ne .Width 640) (ne .Height 360) -}}{{- $thumb = .Fill "640x360 q75" -}}{{- end -}}
  <img src="{{ $thumb.RelPermalink }}" width="640" height="360" alt="" loading="lazy">
  {{- else -}}
  <img src="{{ .RelPermalink }}" alt="" loading="lazy">
  {{- end -}}
</a>
{{- end }}
<div class="card-body">
{{ with .GetTerms "tags" }}<p class="card-tags">{{ range . }}<a href="{{ .RelPermalink }}">{{ .LinkTitle }}</a> {{ end }}</p>{{ end }}
<h2 class="card-title"><a href="{{ .RelPermalink }}">{{ .Title }}</a></h2>
<p class="card-excerpt">{{ .Summary | plainify | truncate 150 }}</p>
<p class="card-meta"><time>{{ .Date.Format "January 2, 2006" }}</time>{{ with .Params.author }} · {{ . }}{{ end }}</p>
</div>
</article>
"""

HOME = """\
{{ define "main" }}
<h1 class="page-title">{{ site.Title }}</h1>
<div class="intro">{{ .Content }}</div>
{{ $paginator := .Paginate (where site.RegularPages "Type" "posts") }}
<div class="card-grid">
{{ range $paginator.Pages }}{{ partial "card.html" . }}{{ end }}
</div>
{{ template "_internal/pagination.html" . }}
{{ end }}
"""

SINGLE = """\
{{ define "main" }}
<article class="post" data-pagefind-body>
<h1>{{ .Title }}</h1>
<p class="post-meta"><time>{{ .Date.Format "January 2, 2006" }}</time>
{{- range .GetTerms "authors" }} · <a href="{{ .RelPermalink }}">{{ .LinkTitle }}</a>{{ end }}
{{- with .Params.tags }} ·{{ range $.GetTerms "tags" }} <a class="tag" href="{{ .RelPermalink }}">{{ .LinkTitle }}</a>{{ end }}{{ end }}</p>
{{ .Content }}
</article>
{{ end }}
"""

LIST = """\
{{ define "main" }}
<h1 class="page-title">{{ .Title }}</h1>
{{ .Content }}
{{ $paginator := .Paginate .Pages.ByDate.Reverse }}
<div class="card-grid">
{{ range $paginator.Pages }}{{ partial "card.html" . }}{{ end }}
</div>
{{ template "_internal/pagination.html" . }}
{{ end }}
"""

TERMS = """\
{{ define "main" }}
<h1 class="page-title">{{ .Title }}</h1>
""" + TERM_SORT + """\
<p class="term-list">
{{ range .Data.Terms.Alphabetical }}<a class="chip" href="{{ .Page.RelPermalink }}">{{ .Page.Title }} <span>{{ .Count }}</span></a>
{{ end }}</p>
{{ end }}
"""

ARCHIVES = """\
{{ define "main" }}
<h1 class="page-title">{{ .Title }}</h1>
{{ range (where site.RegularPages "Type" "posts").GroupByDate "2006" }}
<h2>{{ .Key }}</h2>
<ul class="archives">
{{ range .Pages }}<li><time>{{ .Date.Format "2006-01-02" }}</time> <a href="{{ .RelPermalink }}">{{ .Title }}</a></li>
{{ end }}</ul>
{{ end }}
{{ end }}
"""

SEARCH = """\
{{ define "main" }}
<h1 class="page-title">Search</h1>
{{- /* Pagefind's Component UI (its recommended integration since 1.5),
       composed as input + summary + in-page results rather than the
       searchbox dropdown, so results stay on the page -- scrollable and
       findable with the browser's own search. The elements find the
       index bundle at /pagefind/ on their own. */}}
<link rel="stylesheet" href="{{ "pagefind/pagefind-component-ui.css" | relURL }}">
<script type="module" src="{{ "pagefind/pagefind-component-ui.js" | relURL }}"></script>
<div id="search">
<pagefind-input autofocus placeholder="Search the archive"></pagefind-input>
<pagefind-summary></pagefind-summary>
<pagefind-results></pagefind-results>
</div>
<script>
window.addEventListener("load", function () {
  if (!customElements.get("pagefind-input")) {
    document.getElementById("search").textContent =
      "Search index not built yet: run `pagefind --site public` after `hugo`.";
    return;
  }
  // shareable searches: mirror the query into ?q=, restore it on load
  var input = document.querySelector("pagefind-input input");
  if (!input) return;
  var q = new URLSearchParams(location.search).get("q");
  if (q) {
    input.value = q;
    input.dispatchEvent(new Event("input", { bubbles: true }));
  }
  input.addEventListener("input", function () {
    var url = new URL(location);
    if (input.value) url.searchParams.set("q", input.value);
    else url.searchParams.delete("q");
    history.replaceState(null, "", url);
  });
});
</script>
{{ end }}
"""

# Full-content feeds, like the publication's original Medium feed:
# summary in <description>, complete body in <content:encoded>, capped by
# services.rss.limit. Feed readers resolve relative URLs unreliably, so
# root-relative src/href become absolute against baseURL, and the
# responsive srcset/sizes attributes (meaningless in a feed) are
# stripped. Written for site and per-term feeds alike, and also when a
# real theme is configured -- feed policy is content policy, not styling.
RSS = """\
{{- $pages := site.RegularPages -}}
{{- if not .IsHome }}{{ $pages = .Pages }}{{ end -}}
{{- with site.Config.Services.RSS.Limit -}}
{{- if ge . 1 }}{{ $pages = $pages | first . }}{{ end -}}
{{- end -}}
{{- /* a literal <?xml would be HTML-escaped by the template engine */ -}}
{{ printf "<?xml version=\\"1.0\\" encoding=\\"utf-8\\" standalone=\\"yes\\"?>" | safeHTML }}
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>{{ if not .IsHome }}{{ .Title }} · {{ end }}{{ site.Title }}</title>
    <link>{{ .Permalink }}</link>
    <description>{{ site.Params.description }}</description>
    <generator>Hugo</generator>
    {{ with index $pages 0 }}<lastBuildDate>{{ .Date.Format "Mon, 02 Jan 2006 15:04:05 -0700" }}</lastBuildDate>{{ end }}
    <atom:link href="{{ .Permalink }}index.xml" rel="self" type="application/rss+xml" />
    {{ range $pages }}
    <item>
      <title>{{ .Title }}</title>
      <link>{{ .Permalink }}</link>
      <pubDate>{{ .Date.Format "Mon, 02 Jan 2006 15:04:05 -0700" }}</pubDate>
      {{ with .Params.author }}<dc:creator>{{ . }}</dc:creator>{{ end }}
      <guid>{{ .Permalink }}</guid>
      <description>{{ with .Description }}{{ . }}{{ else }}{{ .Summary | plainify }}{{ end }}</description>
      {{- /* absolutize root-relative URLs against baseURL and the gif/svg
             passthroughs' page-relative images/ against this post's URL */}}
      <content:encoded>{{ .Content | replaceRE ` (srcset|sizes)="[^"]*"` "" | replaceRE `(src|href)="(/[^"]*)"` (printf `$1="%s$2"` (strings.TrimSuffix "/" site.BaseURL)) | replaceRE `(src|href)="(images/[^"]*)"` (printf `$1="%s$2"` .Permalink) | html }}</content:encoded>
    </item>
    {{ end }}
  </channel>
</rss>
"""

# Body images: serve responsive, lazily-loaded variants (webp encodes of
# the still originals; gif/svg/webp sources pass through untouched).
RENDER_IMAGE = """\
{{- $img := .Page.Resources.Get .Destination -}}
{{- if and $img (eq $img.MediaType.MainType "image") (not (in (slice "gif" "svg" "webp") $img.MediaType.SubType)) -}}
{{- $srcset := slice -}}
{{- range $w := slice 480 736 1104 -}}
{{- if ge $img.Width $w -}}
{{- $v := $img.Resize (printf "%dx q75 webp" $w) -}}
{{- $srcset = $srcset | append (printf "%s %dw" $v.RelPermalink $v.Width) -}}
{{- end -}}
{{- end -}}
<img src="{{ $img.RelPermalink }}"{{ with $srcset }} srcset="{{ delimit . ", " }}" sizes="(max-width: 800px) 100vw, 736px"{{ end }} width="{{ $img.Width }}" height="{{ $img.Height }}" loading="lazy" alt="{{ .PlainText }}">
{{- else -}}
<img src="{{ .Destination | safeURL }}" alt="{{ .PlainText }}" loading="lazy">
{{- end -}}
"""

# The dark palette, emitted twice below: once for an explicit picker
# choice (data-theme="dark") and once for a dark system scheme with no
# stored choice. --accent-dark doubles as the link color, so dark mode
# lightens it to keep contrast against the dark cards.
_DARK_PALETTE = """\
  --accent-dark: #f08b4b; --ink: #e8e6e3; --soft: #c9c6c2; --muted: #9b9791;
  --bg: #131313; --card: #1e1e1e; --line: #333333; --code-bg: #2a2a2a;
  --mark: #7a4114; color-scheme: dark;
"""

CSS = """\
/* Light is the default palette. The header picker pins an explicit
   choice as data-theme on <html> (persisted in localStorage); with no
   attribute, prefers-color-scheme decides -- the "system" setting. */
:root { --accent: #f37726; --accent-dark: #c85a11; --ink: #1c1c1c;
        --soft: #444444; --muted: #6a6a6a; --bg: #f4f4f4; --card: #ffffff;
        --line: #e2e2e2; --code-bg: #f6f6f6; --mark: #fbd6bc;
        color-scheme: light; }
:root[data-theme="dark"] {
""" + _DARK_PALETTE + """\
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
""" + _DARK_PALETTE + """\
  }
}
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--ink);
       font: 1rem/1.65 system-ui, -apple-system, "Segoe UI", sans-serif; }
.wrap { max-width: 72rem; margin: 0 auto; padding: 0 1.25rem; }
a { color: var(--accent-dark); text-decoration: none; }
a:hover { text-decoration: underline; }

.site-header { background: var(--card); border-bottom: 1px solid var(--line); }
.site-header .bar { display: flex; align-items: center; justify-content: space-between;
                    flex-wrap: wrap; gap: .5rem; padding-top: .9rem; padding-bottom: .9rem; }
.site-title { font-size: 1.25rem; font-weight: 700; color: var(--ink);
              display: flex; align-items: center; gap: .55rem; }
.site-title img { height: 2.1rem; width: auto; }
.site-header nav a { margin-left: 1.25rem; color: var(--soft); font-weight: 500; }
.site-header nav a:hover { color: var(--accent-dark); }

.theme-picker { display: inline-flex; vertical-align: middle; gap: .15rem;
                margin-left: 1.25rem; padding: .15rem;
                border: 1px solid var(--line); border-radius: 999px; }
.theme-picker[hidden] { display: none; }
.theme-picker button { display: inline-flex; align-items: center;
                       justify-content: center; width: 1.6rem; height: 1.6rem;
                       padding: 0; border: 0; border-radius: 999px;
                       background: none; color: var(--muted); cursor: pointer; }
.theme-picker button:hover { color: var(--accent-dark); }
.theme-picker button[aria-pressed="true"] { background: var(--bg);
                                            color: var(--ink); }
.theme-picker svg { width: 1rem; height: 1rem; }

.page-title { font-size: 2.4rem; font-weight: 400; margin: 2.2rem 0 1rem; }
.intro { max-width: 46rem; color: var(--muted); margin-bottom: 2rem; }

.card-grid { display: grid; gap: 1.5rem; margin: 1rem 0 2.5rem;
             grid-template-columns: repeat(auto-fill, minmax(19rem, 1fr)); }
.card { background: var(--card); border-radius: 8px; overflow: hidden;
        box-shadow: 0 1px 3px rgba(0,0,0,.09), 0 4px 14px rgba(0,0,0,.05);
        display: flex; flex-direction: column; }
.card-cover { display: block; aspect-ratio: 16/9; background: var(--bg); }
.card-cover img { width: 100%; height: 100%; object-fit: cover; display: block; }
.card-body { padding: 1.1rem 1.25rem 1.25rem; display: flex;
             flex-direction: column; flex: 1; }
.card-tags { margin: 0 0 .35rem; }
.card-tags a { color: var(--accent-dark); font-size: .82rem; font-weight: 600;
               margin-right: .6rem; }
.card-title { margin: 0 0 .5rem; font-size: 1.3rem; line-height: 1.3; }
.card-title a { color: var(--ink); }
.card-excerpt { margin: 0; color: var(--muted); font-size: .95rem; flex: 1; }
.card-meta { margin: 1rem 0 0; color: var(--muted); font-size: .85rem; }

.post { background: var(--card); border-radius: 8px; margin: 2rem auto 3rem;
        padding: 2.5rem clamp(1.25rem, 5vw, 3.5rem); max-width: 52rem;
        box-shadow: 0 1px 3px rgba(0,0,0,.09), 0 4px 14px rgba(0,0,0,.05); }
.post h1 { font-size: 2.1rem; line-height: 1.25; margin: 0 0 .5rem; }
.post-meta { color: var(--muted); margin: 0 0 2rem; }
.post-meta .tag::before { content: "#"; opacity: .6; }
.post img { max-width: 100%; height: auto; border-radius: 4px; }
.post pre { overflow-x: auto; padding: 1rem; background: var(--code-bg);
            border-radius: 6px; font-size: .9rem; }
.post code { background: var(--code-bg); }
.post blockquote { margin-left: 0; padding-left: 1rem;
                   border-left: 3px solid var(--accent); color: var(--soft); }
.post figcaption, .post em img + em { color: var(--muted); }

.term-list { display: flex; flex-wrap: wrap; gap: .6rem; margin: 1.5rem 0 3rem; }
.chip { background: var(--card); border: 1px solid var(--line); border-radius: 999px;
        padding: .35rem .9rem; color: var(--ink); }
.chip span { color: var(--muted); font-size: .85em; }
.chip:hover { border-color: var(--accent); text-decoration: none; }

.term-sort { margin: 1.5rem 0 0; color: var(--muted); font-size: .9rem; }
.term-sort[hidden] { display: none; }
.term-sort button { border: 1px solid var(--line); border-radius: 999px;
                    background: var(--card); color: var(--soft); font: inherit;
                    padding: .15rem .8rem; margin-left: .35rem; cursor: pointer; }
.term-sort button:hover { border-color: var(--accent); }
.term-sort button[aria-pressed="true"] { border-color: var(--accent);
                                         color: var(--ink); }
/* ~, not +: the snippet's script tag sits between the two */
.term-sort ~ .term-list { margin-top: .9rem; }

ul.pagination { display: flex; justify-content: center; gap: .25rem;
                list-style: none; padding: 0; margin: 0 0 3rem; }
ul.pagination .page-link { display: inline-block; padding: .35rem .8rem;
                           background: var(--card); border-radius: 6px; color: var(--ink); }
ul.pagination .active .page-link { background: var(--accent); color: #fff; }

.archives { list-style: none; padding: 0; margin: 1rem 0 2rem; }
.archives time { color: var(--muted); font-variant-numeric: tabular-nums;
                 margin-right: .6rem; }
.archives a { color: var(--ink); }

/* Pagefind's component CSS boosts every selector to ID-level specificity
   (its :is(*, #\\#) prefix) so host styles lose by default; it leaves
   !important to the host page as the intended override lever. Orange is
   reserved for the highlighted matches; article titles are set off from
   the per-section heading hits typographically -- large bold vs small
   semibold, both in neutral ink. */
#search { margin: 0 0 3rem;
          /* The component styles itself from --pf-* custom properties
             (light values on :root; it does not follow
             prefers-color-scheme on its own). Redefining them here from
             the site tokens makes the search UI track whichever palette
             is active. */
          --pf-text: var(--ink); --pf-text-secondary: var(--soft);
          --pf-text-muted: var(--muted); --pf-background: var(--card);
          --pf-border: var(--line); --pf-skeleton: var(--code-bg);
          --pf-hover: var(--code-bg); --pf-mark: var(--ink); }
#search mark { color: inherit; border-radius: 2px; padding: 0 .12em;
               background: var(--mark) !important; }
#search .pf-result-title { margin-bottom: .2rem; }
#search .pf-result-link { font-size: 1.25rem !important;
                          font-weight: 700 !important;
                          color: var(--ink) !important; }
#search .pf-result-excerpt { color: var(--soft) !important; }
#search .pf-heading-link { font-size: .92rem !important;
                           font-weight: 600 !important;
                           color: var(--ink) !important; }
#search .pf-heading-excerpt { color: var(--muted) !important;
                              font-size: .9rem !important; }
.site-footer { color: var(--muted); font-size: .85rem; padding-top: 1rem;
               padding-bottom: 2.5rem; }
"""

TEMPLATES = {
    "layouts/_default/baseof.html": BASEOF,
    "layouts/partials/card.html": CARD,
    "layouts/index.html": HOME,
    "layouts/_default/single.html": SINGLE,
    "layouts/_default/list.html": LIST,
    "layouts/_default/taxonomy.html": LIST,
    "layouts/_default/terms.html": TERMS,
    "layouts/_default/archives.html": ARCHIVES,
    "layouts/_default/search.html": SEARCH,
    "layouts/_default/_markup/render-image.html": RENDER_IMAGE,
    "static/css/style.css": CSS,
}


def front_matter(url: str, post: dict, cover: str | None = None) -> str:
    front = {"title": post["title"]}
    if post.get("date"):
        front["date"] = post["date"]
    if post.get("updated"):
        front["lastmod"] = post["updated"]
    if post.get("description"):
        front["description"] = post["description"]
    if post.get("tags"):
        front["tags"] = post["tags"]
    if post.get("author"):
        front["authors"] = [post["author"]]      # the author taxonomy
        front["author"] = post["author"]         # per-post byline (Dream)
        if post.get("author_url"):
            front["authorlink"] = post["author_url"]
    if cover:               # bundle resource: Dream's card and og:image
        front["cover"] = cover
        front["images"] = [cover]
    front["aliases"] = [path for path, _ in old_paths(post, url)]
    return json.dumps(front, indent=2, ensure_ascii=False) + "\n\n"


def _toml_params(params: dict) -> str:
    """[params] as TOML: flat keys first, dict values as sub-tables whose
    dict entries render as inline tables (Dream's navItems form). Values
    go through JSON, whose scalar/list syntax TOML shares."""
    j = lambda v: json.dumps(v, ensure_ascii=False)
    flat, tables = [], []
    for key, value in params.items():
        if isinstance(value, dict):
            rows = [f"[params.{key}]"]
            for name, item in value.items():
                if isinstance(item, dict):
                    inner = ", ".join(f"{k} = {j(v)}" for k, v in item.items())
                    rows.append(f"{name} = {{ {inner} }}")
                else:
                    rows.append(f"{name} = {j(item)}")
            tables.append("\n".join(rows))
        else:
            flat.append(f"{key} = {j(value)}")
    return "\n\n".join(["[params]\n" + "\n".join(flat)] + tables)


def dream_params(manifest: dict, config: dict) -> dict:
    """Dream's conventions, derived from the archive: RSS in the nav, an
    Authors item for the author taxonomy, the site's first year."""
    years = [p["date"][:4] for p in manifest.values() if p.get("date")]
    params = {"headerTitle": config["title"], "author": config["title"],
              "rss": True}
    if years:
        params["siteStartYear"] = int(min(years))
    params["navItems"] = {
        "authors": {"href": "/authors", "icon": "people", "title": "Authors"}}
    return params


def build_site(out):
    manifest, config = load_site_inputs(out)
    stems = page_stems(manifest)
    hugo_config = config.get("hugo", {})
    theme = hugo_config.get("theme")
    dream = theme == "dream"
    site = out / "site-hugo"
    clean_site(site, keep=("public", "resources", "themes"))

    (site / "content").mkdir(parents=True)
    (site / "content" / "_index.md").write_text(
        json.dumps({"title": config["title"]}) + "\n\n"
        + (config.get("intro", "") + "\n" if config.get("intro") else ""),
        encoding="utf-8")
    if dream:
        # Dream renders /posts as an archives timeline and turns an empty
        # search section into its built-in title+description search page
        (site / "content" / "posts").mkdir()
        (site / "content" / "posts" / "_index.md").write_text(
            json.dumps({"title": "Archives"}) + "\n", encoding="utf-8")
        (site / "content" / "search").mkdir()
        (site / "content" / "search" / "_index.md").write_text("{}\n",
                                                               encoding="utf-8")
    elif not theme:
        # the built-in theme's Pagefind search page (see SEARCH) and
        # year-grouped archives timeline
        (site / "content" / "search.md").write_text(
            json.dumps({"title": "Search", "layout": "search",
                        "url": "/search/"}) + "\n", encoding="utf-8")
        (site / "content" / "archives.md").write_text(
            json.dumps({"title": "Archives", "layout": "archives",
                        "url": "/archives/"}) + "\n", encoding="utf-8")
    try:
        from PIL import Image                      # noqa: F401
        have_pillow = True
    except ImportError:
        have_pillow = False
        print("pillow not installed: card covers keep full-size images "
              "(`pip install pillow` and re-run for 640x360 thumbnails)",
              file=sys.stderr)
    covers = {url: cover for url, p in manifest.items()
              if (cover := pick_cover(p, out / p["dir"]))}
    pages = export_content(
        out, site, manifest, stems,
        lambda url, p: front_matter(url, p,
                                    cover=("images/cover.jpg" if have_pillow
                                           else covers.get(url))
                                    if url in covers else None),
        placer=ImagePlacer(out, config))
    if have_pillow:
        bake_cover_thumbnails(out, site, manifest, stems, covers)

    params = {"description": config.get("description", "")}
    if dream:
        params.update(dream_params(manifest, config))
    # "avatar" (site.json top level, or hugo section): archive-relative
    # path of a hand-picked site logo, shown in the header; copied into
    # the site so the site stays self-contained
    avatar = hugo_config.get("avatar") or config.get("avatar")
    if avatar:
        src = out / avatar
        if src.is_file():
            dst = site / "static" / "img" / ("avatar" + src.suffix)
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            params["avatar"] = f"img/{dst.name}"
        else:
            print(f"avatar not found, skipped: {src}", file=sys.stderr)
    params.update(hugo_config.get("params", {}))
    (site / "hugo.toml").write_text(CONFIG.format(
        base_url=json.dumps(config.get("base_url", "https://example.org/")),
        title=json.dumps(config["title"], ensure_ascii=False),
        locale=json.dumps(hugo_config.get("locale", "en")),
        theme=f"theme = {json.dumps(theme)}\n" if theme else "",
        params=_toml_params(params),
    ), encoding="utf-8")
    if not theme:               # the theme provides layouts and styling
        for rel, text in TEMPLATES.items():
            path = site / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    rss = site / "layouts" / "_default" / "rss.xml"
    rss.parent.mkdir(parents=True, exist_ok=True)
    rss.write_text(RSS, encoding="utf-8")
    write_redirects_csv(site, manifest, stems, lambda stem: f"/posts/{stem}/")
    print(f"hugo done: {pages}/{len(manifest)} pages -> {site}", file=sys.stderr)
    if theme and not (site / "themes" / theme).is_dir():
        repo = hugo_config.get("theme_repo", "<theme repository>")
        print(f"theme missing (kept across regenerations): "
              f"git clone {repo} {site / 'themes' / theme}", file=sys.stderr)
    print(f"render it with: cd {site} && hugo server   (or: hugo; then "
          "`pagefind --site public` for search)", file=sys.stderr)
    return site


def cmd_hugo(args):
    build_site(args.out)
