"""The myst step: build a MyST (mystmd) site in <out>/site/ from the
converted archive -- one page per post with its images, a chronological
landing page, a year-grouped table of contents, and a site-level redirect
map.

Works from posts.json and <out>/posts/ alone (run convert first), so the
site is as reproducible as the posts are: raw/ + fixups/ -> convert ->
posts/ -> myst -> site/. Never touches the network; rendering the site
(`myst start` or `myst build --html` inside <out>/site/) is mystmd's job,
not this step's.

The posts/ layer stays generator-agnostic Markdown; everything
MyST-specific happens here: front matter is reshaped to MyST's schema
(authors, tags), page URLs are chosen (each page's filename is its URL
slug), links between posts in the publication are rewritten from Medium
URLs to site-relative page links, prose MyST would misparse is escaped,
and redirects.csv maps every old inbound path to its new page URL.

Site-wide text (title, description, the landing-page intro) comes from an
optional hand-written <out>/site.json, so it is versioned with the archive
and survives regeneration. The machinery shared with the other site
exporters (hugo, zola, pelican) lives in sites.py.
"""

import json
import re
import sys
from pathlib import Path

from .sites import (ImagePlacer, LinkMap, by_year, clean_site,
                    load_site_inputs, page_stems, read_post_body,
                    rewrite_body as _rewrite, write_redirects_csv)

# Segments MyST-escaping must leave alone: inline code, link destinations,
# autolinks. Everything else in a prose line is text MyST will parse.
PROTECT_RE = re.compile(r"(`+[^`]*`+|\]\([^)\s]*\)|<https?://[^>\s]+>)")
AT_RE = re.compile(r"(?<![\w\\])@(?=\w)")          # @handle, not an email's @
DOLLAR_RE = re.compile(r"(?<!\\)\$")


def _yml(value) -> str:
    """A scalar or flow list as YAML, via JSON (valid YAML)."""
    return json.dumps(value, ensure_ascii=False)


def escape_prose(line: str) -> str:
    """Escape Markdown that plain Markdown treats as text but MyST parses
    as syntax: @handle mentions (MyST citations -- GitHub handles in
    contributor lists would silently become unresolved cites) and $
    (dollar math -- "grants of $10,000 to $20,000" would render the span
    between the dollars as math). Inline code, link destinations and
    autolinks pass through untouched."""
    parts = PROTECT_RE.split(line)
    return "".join(p if i % 2 else DOLLAR_RE.sub(r"\\$", AT_RE.sub(r"\\@", p))
                   for i, p in enumerate(parts))


def rewrite_body(markdown: str, links: LinkMap, prefix: str) -> str:
    """Point links at other posts of the publication to their site pages
    instead of Medium, and escape prose MyST would misparse. prefix is
    the path from the referring page's directory to site/posts/ ("../"
    for a post page, "posts/" for the landing page)."""
    def target_for(url):
        hit = links.page_for(url)
        if hit is None:
            return None
        d, stem, frag = hit
        return f"{prefix}{d}/{stem}.md" + (f"#{frag}" if frag else "")
    return _rewrite(markdown, target_for, escape_prose)


def page_front_matter(post: dict) -> str:
    """The post's front matter reshaped to MyST's schema. Archive
    provenance fields (original_url, medium_id, body_source, ...) stay in
    posts/ and posts.json; a site page carries only what MyST renders."""
    lines = [f"title: {_yml(post['title'])}"]
    if post.get("description"):
        lines.append(f"description: {_yml(post['description'])}")
    if post.get("date"):
        # bare date: MyST ignores (and warns about) a time component
        lines.append(f"date: {_yml(post['date'][:10])}")
    if post.get("author"):
        if " " in post["author"].strip():
            lines.append(f"authors:\n  - name: {_yml(post['author'])}")
        else:                    # mononym; MyST would warn parsing it
            lines.append("authors:\n  - name:\n"
                         f"      literal: {_yml(post['author'])}")
        if post.get("author_url"):
            lines.append(f"    url: {_yml(post['author_url'])}")
    if post.get("tags"):
        lines.append(f"tags: {_yml(post['tags'])}")
    return "---\n" + "\n".join(lines) + "\n---\n\n"


def write_myst_yml(site: Path, manifest: dict, stems: dict, config: dict):
    lines = ["# Generated by `medium-archive myst`; do not edit.",
             "# Site title/description/intro come from <out>/site.json.",
             "version: 1",
             "project:",
             f"  title: {_yml(config['title'])}"]
    if config.get("description"):
        lines.append(f"  description: {_yml(config['description'])}")
    lines += ["  toc:",
              "    - file: index.md"]
    for year, posts in by_year(manifest):
        lines.append(f"    - title: {_yml(year)}")
        lines.append("      children:")
        for url, p in posts:
            lines.append(f"        - file: posts/{Path(p['dir']).name}/{stems[url]}.md")
    lines += ["site:",
              "  template: book-theme",
              f"  title: {_yml(config['title'])}"]
    (site / "myst.yml").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_landing(site: Path, manifest: dict, stems: dict, config: dict):
    esc = lambda t: escape_prose(t.replace("[", "\\[").replace("]", "\\]"))
    lines = ["---", f"title: {_yml(config['title'])}", "---", ""]
    if config.get("intro"):
        lines += [config["intro"].rstrip(), ""]
    for year, posts in by_year(manifest):
        lines += [f"## {year}", ""]
        for url, p in posts:
            date = (p.get("date") or "")[:10]
            entry = f"- {date} — [{esc(p['title'] or url)}]" \
                    f"(posts/{Path(p['dir']).name}/{stems[url]}.md)"
            if p.get("author"):
                entry += f" · {esc(p['author'])}"
            lines.append(entry)
        lines.append("")
    (site / "index.md").write_text("\n".join(lines), encoding="utf-8")


def build_site(out: Path) -> Path:
    manifest, config = load_site_inputs(out)
    stems = page_stems(manifest)
    links = LinkMap(manifest, stems)
    # Rebuild from scratch, but keep mystmd's _build/ (its template cache
    # and rendered output) so regenerating doesn't force a re-download.
    site = out / "site"
    clean_site(site, keep=("_build",))
    (site / "posts").mkdir(parents=True)

    placer = ImagePlacer(out, config)
    placer.warm(out, manifest)
    pages = 0
    for url, p in manifest.items():
        body = read_post_body(out / p["dir"])
        if body is None:
            print(f"skipping (no index.md; re-run convert): {p['dir']}",
                  file=sys.stderr)
            continue
        body = rewrite_body(body, links, "../")
        page_dir = site / "posts" / Path(p["dir"]).name
        page_dir.mkdir()
        (page_dir / f"{stems[url]}.md").write_text(
            page_front_matter(p) + body, encoding="utf-8")
        images = out / p["dir"] / "images"
        if images.is_dir():
            (page_dir / "images").mkdir()
            for img in sorted(images.iterdir()):
                placer.place(img, page_dir / "images" / img.name)
        pages += 1

    placer.report()
    write_landing(site, manifest, stems, config)
    write_myst_yml(site, manifest, stems, config)
    write_redirects_csv(site, manifest, stems, lambda stem: f"/{stem}")
    print(f"myst done: {pages}/{len(manifest)} pages -> {site}", file=sys.stderr)
    print(f"render it with: cd {site} && myst start   (or: myst build --html)",
          file=sys.stderr)
    return site


def cmd_myst(args):
    build_site(args.out)
