"""The pelican step: build a Pelican site in <out>/site-pelican/ from
the converted archive. Same reproducibility contract as the myst step
(see sites.py); render with `pelican -l` (serve) or `pelican` (build)
inside <out>/site-pelican/ (https://getpelican.com, `pip install
pelican markdown`).

Each post becomes content/posts/<stem>/index.md with its images beside
it; image references are rewritten to Pelican's `{attach}` form so the
files publish next to the article at /posts/<stem>/. Body images load
lazily (a small Markdown extension embedded in the generated config)
and are served responsively: after each build the embedded plugin
encodes webp variants of every still body image at the same widths as
the hugo theme's render hook (480/736/1104, never upscaled,
mtime-cached) and rewrites the article's img tags with srcset/sizes
and real width/height. Metadata uses Pelican's `Key: value` header format; tags and
authors are first-class in Pelican, so tag/author listing pages and
Atom feeds (site-wide and per tag/author) come out of the box.

The exporter writes its own theme -- the card-grid blog shared with
the hugo step, light and dark palettes and the header's
light/dark/system picker included: paginated home of cover-image
cards, article pages, tag/author card listings, chip indexes, an
archives timeline, and a /search/ page wired to Pagefind
(run `pagefind --site output` after `pelican` for full-text search with
highlighted, in-context excerpts). Card covers are 640x360 thumbnails
generated at export time when Pillow is installed (`pip install
pillow`); without it, cards use the full-size image.

Pelican has no built-in equivalent of Hugo's and Zola's aliases, so the
generated config embeds a small plugin: after each build it reads the
exported redirects.csv and writes a meta-refresh redirect stub at every
old inbound path (Medium slug+id, /p/<id>, Ghost-era) -- the same stub
pages Hugo renders for aliases, working on any static host.
"""

import json
import re
import sys

from .hugo import CSS as CARD_CSS  # hugo and pelican share the look
from .hugo import THEME_INIT, THEME_PICKER
from .sites import (ImagePlacer, clean_site, export_content,
                    load_site_inputs, page_stems, pick_cover,
                    write_redirects_csv)

CONFIG = """\
# Generated by `medium-archive pelican`; do not edit.
# Site title/description/intro come from <out>/site.json.
SITENAME = {title}
SITESUBTITLE = {description}
SITEURL = {base_url}
TIMEZONE = "UTC"
DEFAULT_LANG = "en"
DEFAULT_DATE_FORMAT = "%B %d, %Y"

PATH = "content"
THEME = "theme"
ARTICLE_PATHS = ["posts"]
STATIC_PATHS = ["posts"]        # colocated images, placed via {{attach}}
PAGE_PATHS = []
# directory-style URLs throughout, matching the hugo build's scheme
ARTICLE_URL = "posts/{{slug}}/"
ARTICLE_SAVE_AS = "posts/{{slug}}/index.html"
TAG_URL = "tags/{{slug}}/"
TAG_SAVE_AS = "tags/{{slug}}/index.html"
TAGS_URL = "tags/"
TAGS_SAVE_AS = "tags/index.html"
AUTHOR_URL = "authors/{{slug}}/"
AUTHOR_SAVE_AS = "authors/{{slug}}/index.html"
AUTHORS_URL = "authors/"
AUTHORS_SAVE_AS = "authors/index.html"
ARCHIVES_URL = "archives/"
ARCHIVES_SAVE_AS = "archives/index.html"
PAGINATION_PATTERNS = (
    (1, "{{url}}", "{{save_as}}"),
    (2, "{{base_name}}/page/{{number}}/", "{{base_name}}/page/{{number}}/index.html"),
)
DEFAULT_PAGINATION = 24
DEFAULT_CATEGORY = "posts"
SLUGIFY_SOURCE = "basename"     # slugs are explicit in each article anyway
DIRECT_TEMPLATES = ["index", "tags", "authors", "archives"]
TEMPLATE_PAGES = {{"search.html": "search/index.html"}}
CATEGORY_URL = ""               # tags and authors classify posts;
CATEGORY_SAVE_AS = ""           # the category axis stays unused
AVATAR = {avatar}

FEED_ALL_ATOM = "feeds/all.atom.xml"
FEED_MAX_ITEMS = 20             # a feed announces new posts; the site
                                # itself is the archive
CATEGORY_FEED_ATOM = None
TAG_FEED_ATOM = "feeds/tag-{{slug}}.atom.xml"
AUTHOR_FEED_ATOM = "feeds/author-{{slug}}.atom.xml"
AUTHOR_FEED_RSS = None

from markdown.extensions import Extension as _Extension
from markdown.treeprocessors import Treeprocessor as _Treeprocessor


class _LazyImages(_Extension):
    # body images load lazily, so a reader doesn't fetch every
    # below-the-fold full-resolution image up front
    def extendMarkdown(self, md):
        class _Lazy(_Treeprocessor):
            def run(self, root):
                for img in root.iter("img"):
                    img.set("loading", "lazy")
        md.treeprocessors.register(_Lazy(md), "lazy-images", 5)


MARKDOWN = {{
    "extension_configs": {{
        "markdown.extensions.codehilite": {{"css_class": "highlight"}},
        "markdown.extensions.extra": {{}},
        "markdown.extensions.meta": {{}},
        # heading ids give search results per-section anchors
        "markdown.extensions.toc": {{}},
    }},
    "extensions": [_LazyImages()],
    "output_format": "html5",
}}
"""

# Appended to the config verbatim (not .format()ed): a plugin that gives
# Pelican the redirect stubs Hugo and Zola render for aliases, and the
# responsive body images the hugo theme's render hook produces.
SITE_PLUGIN = '''

STUB = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>{target}</title>
<link rel="canonical" href="{target}">
<meta name="robots" content="noindex">
<meta http-equiv="refresh" content="0; url={target}">
</head><body><a href="{target}">{target}</a></body></html>
"""


def _write_redirect_stubs(pelican_obj):
    # Pelican has no aliases feature, so after each build this writes a
    # meta-refresh stub at every old inbound path from redirects.csv --
    # the exporter's map of Medium slug+id, /p/<id> and Ghost-era paths
    # to the pages this site serves. Works on any static host.
    import csv
    import os
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "redirects.csv"), newline="",
              encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    written = 0
    for row in rows:
        parts = [p for p in row["old_path"].split("/") if p]
        stub = os.path.join(pelican_obj.output_path, *parts, "index.html")
        if os.path.exists(stub):        # never clobber a real page
            continue
        os.makedirs(os.path.dirname(stub), exist_ok=True)
        with open(stub, "w", encoding="utf-8") as fh:
            fh.write(STUB.format(target=SITEURL + row["new_path"]))
        written += 1
    print(f"redirect stubs: {written} written from redirects.csv")


# Responsive body images, like the hugo exporter's render hook: webp
# variants at these widths (never upscaled), advertised via srcset with
# this sizes hint, plus real width/height so the layout cannot shift.
VARIANT_WIDTHS = (480, 736, 1104)
SIZES_ATTR = "(max-width: 800px) 100vw, 736px"
IMG_TAG_RE = None   # compiled on first use
ARTICLE_IMG = r"/?posts/[^/]+/images/[^/]+\\.(?:png|jpe?g)"


def _optimize_article_images(pelican_obj):
    # Rewrite each article's still body images (the constrained pattern
    # this exporter itself emits; gif/svg/webp pass through) to lazily
    # loaded responsive variants. Variants are cached by mtime, so only
    # new or changed images are re-encoded on later builds.
    try:
        from PIL import Image
    except ImportError:
        print("pillow not installed: body images keep their full-size "
              "originals (pip install pillow and rebuild)")
        return
    import glob
    import os
    import re
    tag_re = re.compile(r"<img\\b[^>]*>")
    attr_re = re.compile(r\'([-\\w]+)="([^"]*)"\')
    path_re = re.compile(ARTICLE_IMG + "$", re.I)
    stats = {"variants": 0, "pages": 0}

    here = os.path.dirname(os.path.abspath(__file__))

    def rewrite(match):
        tag = match.group(0)
        attrs = dict(attr_re.findall(tag))
        src = attrs.get("src", "")
        path = src[len(SITEURL):] if SITEURL and src.startswith(SITEURL) else src
        if "srcset" in attrs or not path_re.fullmatch(path):
            return tag
        parts = path.lstrip("/").split("/")
        local = os.path.join(pelican_obj.output_path, *parts)
        # encode from (and cache against) the content-side original:
        # Pelican freshens the output copy's mtime on every build, which
        # would defeat the cache
        source = os.path.join(here, PATH, *parts)
        if not os.path.exists(source):
            source = local
        try:
            with Image.open(source) as im:
                width, height = im.size
                im.load()
                if im.mode == "P":
                    im = im.convert("RGBA")
                elif im.mode not in ("RGB", "RGBA"):
                    im = im.convert("RGB")
                srcset = []
                for vw in VARIANT_WIDTHS:
                    if width < vw:
                        continue
                    variant = os.path.splitext(local)[0] + "-%d.webp" % vw
                    if (not os.path.exists(variant) or
                            os.path.getmtime(variant) < os.path.getmtime(source)):
                        vh = max(1, round(height * vw / width))
                        im.resize((vw, vh), Image.Resampling.LANCZOS).save(
                            variant, "WEBP", quality=75)
                        stats["variants"] += 1
                    srcset.append("%s-%d.webp %dw"
                                  % (os.path.splitext(src)[0], vw, vw))
        except OSError:
            return tag
        extra = ""
        if "width" not in attrs and "height" not in attrs:
            extra += \' width="%d" height="%d"\' % (width, height)
        if srcset:
            extra += \' srcset="%s" sizes="%s"\' % (", ".join(srcset), SIZES_ATTR)
        if not extra:
            return tag
        end = "/>" if tag.endswith("/>") else ">"
        return tag[:-len(end)] + extra + end

    for page in glob.glob(os.path.join(pelican_obj.output_path,
                                       "posts", "*", "index.html")):
        with open(page, encoding="utf-8") as fh:
            html = fh.read()
        rewritten = tag_re.sub(rewrite, html)
        if rewritten != html:
            with open(page, "w", encoding="utf-8") as fh:
                fh.write(rewritten)
            stats["pages"] += 1
    print("responsive images: %(variants)d variants encoded, "
          "%(pages)d pages rewritten" % stats)


class _SitePlugins:
    @staticmethod
    def register():
        from pelican import signals
        signals.finalized.connect(_optimize_article_images)
        signals.finalized.connect(_write_redirect_stubs)


PLUGINS = [_SitePlugins]
'''

BASE = """\
<!DOCTYPE html>
<html lang="{{ DEFAULT_LANG }}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title %}{{ SITENAME }}{% endblock %}</title>
<meta name="description" content="{{ SITESUBTITLE }}">
<link rel="alternate" type="application/atom+xml" href="{{ SITEURL }}/{{ FEED_ALL_ATOM }}" title="{{ SITENAME }}">
""" + THEME_INIT + """\
<link rel="stylesheet" href="{{ SITEURL }}/{{ THEME_STATIC_DIR }}/css/style.css">
</head>
<body>
<header class="site-header"><div class="wrap bar">
<a class="site-title" href="{{ SITEURL }}/">{% if AVATAR %}<img src="{{ SITEURL }}/{{ AVATAR }}" alt="">{% endif %}{{ SITENAME }}</a>
<nav>
<a href="{{ SITEURL }}/">Blog</a>
<a href="{{ SITEURL }}/tags/">Tags</a>
<a href="{{ SITEURL }}/authors/">Authors</a>
<a href="{{ SITEURL }}/archives/">Archives</a>
<a href="{{ SITEURL }}/search/">Search</a>
<a href="{{ SITEURL }}/{{ FEED_ALL_ATOM }}">RSS</a>
""" + THEME_PICKER + """\
</nav>
</div></header>
<main class="wrap">
{% block content %}{% endblock %}
</main>
<footer class="wrap site-footer">{{ SITESUBTITLE }}</footer>
</body>
</html>
"""

MACROS = """\
{% macro card(article) %}
<article class="card">
{% if article.cover %}
<a class="card-cover" href="{{ SITEURL }}/{{ article.url }}"><img src="{{ SITEURL }}/{{ article.url }}{{ article.cover }}" width="640" height="360" alt="" loading="lazy"></a>
{% endif %}
<div class="card-body">
{% if article.tags %}<p class="card-tags">{% for t in article.tags %}<a href="{{ SITEURL }}/{{ t.url }}">{{ t }}</a> {% endfor %}</p>{% endif %}
<h2 class="card-title"><a href="{{ SITEURL }}/{{ article.url }}">{{ article.title }}</a></h2>
<p class="card-excerpt">{{ article.summary | striptags | truncate(150) }}</p>
<p class="card-meta"><time>{{ article.locale_date }}</time>{% if article.author %} · {{ article.author }}{% endif %}</p>
</div>
</article>
{% endmacro %}
"""

PAGINATION = """\
{% if articles_page and articles_page.has_other_pages() %}
<ul class="pagination">
{% if articles_page.has_previous() %}<li><a class="page-link" href="{{ SITEURL }}/{{ articles_previous_page.url }}">← Newer</a></li>{% endif %}
<li class="active"><span class="page-link">Page {{ articles_page.number }} of {{ articles_paginator.num_pages }}</span></li>
{% if articles_page.has_next() %}<li><a class="page-link" href="{{ SITEURL }}/{{ articles_next_page.url }}">Older →</a></li>{% endif %}
</ul>
{% endif %}
"""

INDEX = """\
{% extends "base.html" %}
{% from "macros.html" import card with context %}
{% block content %}
<h1 class="page-title">{{ SITENAME }}</h1>
<div class="card-grid">
{% for article in articles_page.object_list %}{{ card(article) }}{% endfor %}
</div>
{% include "pagination.html" %}
{% endblock %}
"""

ARTICLE = """\
{% extends "base.html" %}
{% block title %}{{ article.title }} · {{ SITENAME }}{% endblock %}
{% block content %}
<article class="post" data-pagefind-body>
<h1>{{ article.title }}</h1>
<p class="post-meta"><time>{{ article.locale_date }}</time>
{%- if article.author %} · <a href="{{ SITEURL }}/{{ article.author.url }}">{{ article.author }}</a>{% endif %}
{%- if article.tags %} ·{% for t in article.tags %} <a class="tag" href="{{ SITEURL }}/{{ t.url }}">{{ t }}</a>{% endfor %}{% endif %}</p>
{{ article.content }}
</article>
{% endblock %}
"""

TAG = """\
{% extends "base.html" %}
{% from "macros.html" import card with context %}
{% block title %}{{ tag }} · {{ SITENAME }}{% endblock %}
{% block content %}
<h1 class="page-title">{{ tag }}</h1>
<div class="card-grid">
{% for article in articles_page.object_list %}{{ card(article) }}{% endfor %}
</div>
{% include "pagination.html" %}
{% endblock %}
"""

AUTHOR = TAG.replace("{{ tag }}", "{{ author }}")

TAGS = """\
{% extends "base.html" %}
{% block title %}Tags · {{ SITENAME }}{% endblock %}
{% block content %}
<h1 class="page-title">Tags</h1>
<p class="term-list">
{% for tag, articles in tags | sort %}<a class="chip" href="{{ SITEURL }}/{{ tag.url }}">{{ tag }} <span>{{ articles | length }}</span></a>
{% endfor %}</p>
{% endblock %}
"""

AUTHORS = """\
{% extends "base.html" %}
{% block title %}Authors · {{ SITENAME }}{% endblock %}
{% block content %}
<h1 class="page-title">Authors</h1>
<p class="term-list">
{% for author, articles in authors %}<a class="chip" href="{{ SITEURL }}/{{ author.url }}">{{ author }} <span>{{ articles | length }}</span></a>
{% endfor %}</p>
{% endblock %}
"""

ARCHIVES = """\
{% extends "base.html" %}
{% block title %}Archives · {{ SITENAME }}{% endblock %}
{% block content %}
<h1 class="page-title">Archives</h1>
{% for year, year_articles in dates | groupby("date.year") | reverse %}
<h2>{{ year }}</h2>
<ul class="archives">
{% for article in year_articles %}<li><time>{{ article.date.strftime("%Y-%m-%d") }}</time> <a href="{{ SITEURL }}/{{ article.url }}">{{ article.title }}</a></li>
{% endfor %}</ul>
{% endfor %}
{% endblock %}
"""

SEARCH = """\
{% extends "base.html" %}
{% block title %}Search · {{ SITENAME }}{% endblock %}
{% block content %}
<h1 class="page-title">Search</h1>
{# Pagefind's Component UI (its recommended integration since 1.5),
   composed as input + summary + in-page results rather than the
   searchbox dropdown, so results stay on the page -- scrollable and
   findable with the browser's own search. The elements find the index
   bundle at /pagefind/ on their own. #}
<link rel="stylesheet" href="{{ SITEURL }}/pagefind/pagefind-component-ui.css">
<script type="module" src="{{ SITEURL }}/pagefind/pagefind-component-ui.js"></script>
<div id="search">
<pagefind-input autofocus placeholder="Search the archive"></pagefind-input>
<pagefind-summary></pagefind-summary>
<pagefind-results></pagefind-results>
</div>
<script>
window.addEventListener("load", function () {
  if (!customElements.get("pagefind-input")) {
    document.getElementById("search").textContent =
      "Search index not built yet: run `pagefind --site output` after `pelican`.";
    return;
  }
  // shareable searches: mirror the query into ?q=, restore it on load
  var input = document.querySelector("pagefind-input input");
  if (!input) return;
  var q = new URLSearchParams(location.search).get("q");
  if (q) {
    input.value = q;
    input.dispatchEvent(new Event("input", { bubbles: true }));
  }
  input.addEventListener("input", function () {
    var url = new URL(location);
    if (input.value) url.searchParams.set("q", input.value);
    else url.searchParams.delete("q");
    history.replaceState(null, "", url);
  });
});
</script>
{% endblock %}
"""

IMAGE_RE = re.compile(r"\]\((images/[^)\s]+)\)")


def attach_images(line: str) -> str:
    """Colocated image references become {attach} links, so Pelican
    copies each file next to its article and rewrites the URL."""
    return IMAGE_RE.sub(r"]({attach}\1)", line)


def _meta(key: str, value: str) -> str:
    return f"{key}: {' '.join(value.split())}\n"    # headers are one line


def make_thumbnail(src, dst) -> bool:
    """640x360 center-cropped JPEG for the summary card, a fraction of
    the archived full-resolution original."""
    from PIL import Image, ImageOps
    try:
        with Image.open(src) as im:
            thumb = ImageOps.fit(im.convert("RGB"), (640, 360),
                                 Image.Resampling.LANCZOS)
            thumb.save(dst, "JPEG", quality=80, optimize=True, progressive=True)
        return True
    except OSError as e:
        print(f"cover thumbnail failed ({e}); using original: {src}",
              file=sys.stderr)
        return False


def build_site(out):
    manifest, config = load_site_inputs(out)
    stems = page_stems(manifest)
    site = out / "site-pelican"
    clean_site(site, keep=("output",))
    (site / "content").mkdir(parents=True)

    try:
        from PIL import Image                      # noqa: F401
        have_pillow = True
    except ImportError:
        have_pillow = False
        print("pillow not installed: card covers keep full-size images "
              "(`pip install pillow` and re-run for 640x360 thumbnails)",
              file=sys.stderr)
    covers = {url: cover for url, p in manifest.items()
              if (cover := pick_cover(p, out / p["dir"]))}

    def front_matter(url, post):
        text = _meta("Title", post["title"] or url)
        if post.get("date"):
            text += _meta("Date", post["date"][:16].replace("T", " "))
        if post.get("updated"):
            text += _meta("Modified", post["updated"][:16].replace("T", " "))
        if post.get("author"):
            text += _meta("Author", post["author"])
        if post.get("tags"):
            text += _meta("Tags", ", ".join(post["tags"]))
        text += _meta("Slug", stems[url])
        if url in covers:
            text += _meta("Cover", "images/cover.jpg" if have_pillow
                          else covers[url])
        if post.get("description"):
            text += _meta("Summary", post["description"])
        return text + "\n"

    pages = export_content(out, site, manifest, stems, front_matter,
                           escape=attach_images,
                           placer=ImagePlacer(out, config))
    if have_pillow:
        import shutil
        for url, cover in covers.items():
            src = out / manifest[url]["dir"] / cover
            dst = site / "content" / "posts" / stems[url] / "images" / "cover.jpg"
            if not make_thumbnail(src, dst):
                shutil.copy2(src, dst)             # extension is cosmetic

    avatar = config.get("avatar")
    avatar_setting = None
    if avatar and (out / avatar).is_file():
        dst = site / "theme" / "static" / "img" / ("avatar" + (out / avatar).suffix)
        dst.parent.mkdir(parents=True, exist_ok=True)
        import shutil
        shutil.copy2(out / avatar, dst)
        avatar_setting = f"theme/img/{dst.name}"

    (site / "pelicanconf.py").write_text(CONFIG.format(
        title=json.dumps(config["title"], ensure_ascii=False),
        description=json.dumps(config.get("description", ""),
                               ensure_ascii=False),
        base_url=json.dumps(config.get("base_url", "").rstrip("/")),
        # json for the string case; None must render as Python's None
        avatar=json.dumps(avatar_setting) if avatar_setting else "None",
    ) + SITE_PLUGIN, encoding="utf-8")

    for rel, text in {"theme/templates/base.html": BASE,
                      "theme/templates/macros.html": MACROS,
                      "theme/templates/pagination.html": PAGINATION,
                      "theme/templates/index.html": INDEX,
                      "theme/templates/article.html": ARTICLE,
                      "theme/templates/tag.html": TAG,
                      "theme/templates/author.html": AUTHOR,
                      "theme/templates/tags.html": TAGS,
                      "theme/templates/authors.html": AUTHORS,
                      "theme/templates/archives.html": ARCHIVES,
                      "theme/templates/search.html": SEARCH,
                      "theme/static/css/style.css": CARD_CSS}.items():
        path = site / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    write_redirects_csv(site, manifest, stems, lambda stem: f"/posts/{stem}/")
    print(f"pelican done: {pages}/{len(manifest)} pages -> {site}",
          file=sys.stderr)
    print(f"render it with: cd {site} && pelican && pagefind --site output"
          "   (or serve with: pelican -l)", file=sys.stderr)
    return site


def cmd_pelican(args):
    build_site(args.out)
