"""The pelican step: build a Pelican site in <out>/site-pelican/ from
the converted archive. Same reproducibility contract as the myst step
(see sites.py); render with `pelican -l` (serve) or `pelican` (build)
inside <out>/site-pelican/ (https://getpelican.com, `pip install
pelican markdown`).

Each post becomes content/posts/<stem>/index.md with its images beside
it; image references are rewritten to Pelican's `{attach}` form so the
files publish next to the article at /posts/<stem>/. Metadata uses
Pelican's `Key: value` header format; tags and authors are first-class
in Pelican, so tag/author listing pages and Atom feeds (site-wide and
per tag/author) come from its built-in theme with no templates to
maintain. Pelican has no alias mechanism, so old inbound paths live only
in the exported redirects.csv; for search, run `pagefind --site output`
after `pelican`.
"""

import json
import re
import sys

from .sites import (clean_site, export_content, load_site_inputs,
                    page_stems, write_redirects_csv)

CONFIG = """\
# Generated by `medium-archive pelican`; do not edit.
# Site title/description/intro come from <out>/site.json.
SITENAME = {title}
SITESUBTITLE = {description}
SITEURL = {base_url}
TIMEZONE = "UTC"
DEFAULT_LANG = "en"

PATH = "content"
ARTICLE_PATHS = ["posts"]
STATIC_PATHS = ["posts"]        # colocated images, placed via {{attach}}
PAGE_PATHS = []
ARTICLE_URL = "posts/{{slug}}/"
ARTICLE_SAVE_AS = "posts/{{slug}}/index.html"
DEFAULT_PAGINATION = 25
DEFAULT_CATEGORY = "posts"
SLUGIFY_SOURCE = "basename"     # slugs are explicit in each article anyway

FEED_ALL_ATOM = "feeds/all.atom.xml"
CATEGORY_FEED_ATOM = None
TAG_FEED_ATOM = "feeds/tag-{{slug}}.atom.xml"
AUTHOR_FEED_ATOM = "feeds/author-{{slug}}.atom.xml"
AUTHOR_FEED_RSS = None
"""

IMAGE_RE = re.compile(r"\]\((images/[^)\s]+)\)")


def attach_images(line: str) -> str:
    """Colocated image references become {attach} links, so Pelican
    copies each file next to its article and rewrites the URL."""
    return IMAGE_RE.sub(r"]({attach}\1)", line)


def _meta(key: str, value: str) -> str:
    return f"{key}: {' '.join(value.split())}\n"    # headers are one line


def build_site(out):
    manifest, config = load_site_inputs(out)
    stems = page_stems(manifest)
    site = out / "site-pelican"
    clean_site(site, keep=("output",))
    (site / "content").mkdir(parents=True)

    def front_matter(url, post):
        text = _meta("Title", post["title"] or url)
        if post.get("date"):
            text += _meta("Date", post["date"][:16].replace("T", " "))
        if post.get("updated"):
            text += _meta("Modified", post["updated"][:16].replace("T", " "))
        if post.get("author"):
            text += _meta("Author", post["author"])
        if post.get("tags"):
            text += _meta("Tags", ", ".join(post["tags"]))
        text += _meta("Slug", stems[url])
        if post.get("description"):
            text += _meta("Summary", post["description"])
        return text + "\n"

    pages = export_content(out, site, manifest, stems, front_matter,
                           escape=attach_images)
    (site / "pelicanconf.py").write_text(CONFIG.format(
        title=json.dumps(config["title"], ensure_ascii=False),
        description=json.dumps(config.get("description", ""),
                               ensure_ascii=False),
        base_url=json.dumps(config.get("base_url", "").rstrip("/")),
    ), encoding="utf-8")
    write_redirects_csv(site, manifest, stems, lambda stem: f"/posts/{stem}/")
    print(f"pelican done: {pages}/{len(manifest)} pages -> {site}",
          file=sys.stderr)
    print(f"render it with: cd {site} && pelican -l   (or: pelican)",
          file=sys.stderr)
    return site


def cmd_pelican(args):
    build_site(args.out)
