"""The README.md written into the archive directory."""

from datetime import datetime, timezone
from pathlib import Path

README_TEMPLATE = """\
# Medium archive of {base}

Generated by `medium-archive` on {date}. This directory is a self-contained
archive of the publication, intended to support migrating the blog off
Medium. It has two layers:

* `raw/` is the **source of truth**: material downloaded from Medium,
  unmodified. It is produced by `medium-archive fetch` and should be backed
  up. It is the only part that cannot be regenerated once the Medium site is
  gone.
* `posts/`, `posts.json` and `redirects.csv` are **derived**: produced by
  `medium-archive convert` from `raw/` alone, with no network access. They
  can be deleted and regenerated at any time (`convert --clean`), and are the
  layer to change when adapting the archive to a new site generator.

## Layout

```
README.md                     this file
raw/
  index.json                  every archived post, keyed by its Medium URL:
                                medium_id, title, published (from the page),
                                sitemap_date, fetched_at, images, in_feed,
                                plus in_export/imported_at/draft for posts
                                merged from a Medium account export
  feed.xml                    the publication RSS feed as downloaded
  <medium_id>/                one directory per post (12-hex Medium id)
    page.html                 the post page, byte-for-byte as served
    export.html               the post's file from a Medium account export,
                                when one was merged in with `import-export`;
                                the editor's own HTML, byte-for-byte
    feed_item.json            the post's RSS item, when the feed covered it
                                at fetch time (title, author, tags, date,
                                content_html). Only ~10 recent posts have one.
    images.json               {{source_url: filename}} for images/
    images/<filename>         full-resolution images referenced by the post
posts.json                    converted posts, keyed by Medium URL; same
                                fields as each post's front matter plus `dir`
redirects.csv                 original_path, medium_id, original_url,
                                new_dir, date, title -- one row per post
posts/
  <YYYY-MM-DD>-<slug>/        one directory per converted post
    index.md                  front matter + Markdown body
    images/<filename>         images copied from raw/, referenced relatively
```

## Front matter (posts/*/index.md)

The front matter block between `---` lines is JSON, which is valid YAML.

| field           | meaning |
|-----------------|---------|
| `title`         | post title |
| `author`        | author display name (JSON-LD, or RSS `dc:creator`) |
| `author_url`    | author profile URL on Medium, if present |
| `date`          | publish timestamp (ISO 8601, UTC) |
| `updated`       | last-modified timestamp, if present |
| `original_url`  | canonical Medium URL of the post |
| `original_path` | path component of `original_url`; what an old inbound link carries |
| `medium_id`     | Medium's hex post id; Medium also resolves `/p/<id>` |
| `slug`          | `original_path` with the id suffix removed |
| `description`   | the subtitle (from the account export) or Medium's summary text |
| `tags`          | tag slugs (RSS categories, scraped tag links, or page state) |
| `images`        | relative paths of images used by the body |
| `body_source`   | `export` (account export), `feed` (RSS `content:encoded`) or `page` (rendered HTML) |

## Redirects

`redirects.csv` has everything needed to map old Medium URLs to the new
site once its URL scheme is decided. Inbound links to Medium posts may use
the full slug+id path (`original_path`) or the short form `/p/<medium_id>`;
both should be redirected.

## Conventions and caveats

* Bodies are Markdown produced by markdownify from Medium HTML. Code
  blocks, lists and headings are generally fine; tables and embeds are
  not: gists and other iframes appear as `[embed: <url>]` links and need
  manual replacement.
* Medium boilerplate ("was originally published in ... on Medium", stat
  tracking pixels, clap/share UI, author header) is stripped in `convert`.
  It is still present in `raw/page.html`.
* Body source preference is `export` > `feed` > `page` (override with
  `convert --prefer-page`). Export bodies are the Medium editor's own HTML
  and convert most faithfully; `page` posts may have leftover chrome, so
  review them. The export contributes the exact first-publish timestamp and
  the untruncated subtitle; tags, the updated date and the publication
  canonical URL still come from the page, so fetching remains worthwhile
  even when an account export is available.
* Links inside bodies that point at other posts in this publication still
  point at Medium; rewrite them using `redirects.csv` when migrating.
* Image filenames are `<NNN>-<original basename>`; the same asset served
  from `miro.medium.com` and `cdn-images-1.medium.com` is stored once.

## Regenerating

    medium-archive {base} --out {out} fetch              # incremental; add new posts
    medium-archive {base} --out {out} compare            # verify page vs export conversion
    medium-archive {base} --out {out} convert --clean    # rebuild posts/ from raw/
"""


def write_readme(out: Path, base: str):
    out.mkdir(parents=True, exist_ok=True)
    (out / "README.md").write_text(README_TEMPLATE.format(
        base=base.rstrip("/"),
        date=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        out=out,
    ), encoding="utf-8")
