"""The README files written into an archive.

Three generated documents, split by what each describes and by how often
that changes:

* ``README.md``, in the archive root, covers the archive proper: ``raw/``,
  the hand-written files beside it, and the two small derived files worth
  committing with them. ``fetch``, ``import-ghost`` and ``convert`` write it.
* ``posts/README.md`` covers the converted posts, and lives inside the
  tree it describes.
* ``SITES.md`` covers the generated site directories.

An archive in version control commits the first and ignores the trees the
other two describe, along with those two files. Keeping the converted
posts and the sites out of the archive README is what lets a change in
how a post converts, or in what a site exporter writes, leave the one
committed README alone.
"""

from pathlib import Path

# The post fields, documented once and rendered into both the archive
# README (which describes posts.json) and the posts README (which
# describes the front matter of the same posts). Passed to str.format
# as an argument, so its braces need no escaping.
FIELDS_TABLE = """\
| field           | meaning |
|-----------------|---------|
| `title`         | post title; one Medium cut short with an ellipsis (an untitled post is titled with its opening heading, capped at about a hundred characters) is completed from that heading |
| `authors`       | the post's authors, each `{"name", "url"}`: display name (JSON-LD, the export byline, or RSS `dc:creator`) and Medium profile URL, if present (null otherwise) |
| `date`          | publish timestamp (ISO 8601, UTC) |
| `updated`       | last-modified timestamp, if present |
| `original_url`  | canonical Medium URL of the post |
| `original_path` | path component of `original_url`; what an old inbound link carries |
| `medium_id`     | Medium's hex post id; Medium also resolves `/p/<id>` |
| `slug`          | `original_path` with the id suffix removed, percent-decoded |
| `canonical_url` | canonical URL the post declared when it names a different page -- a story imported from a gist, or a Ghost-migrated post's pre-migration slug (null otherwise); provenance, not identity |
| `ghost_url`     | the post's URL on the blog's Ghost incarnation, when a capture is attached (null otherwise); old inbound links may carry this path |
| `description`   | the summary alone: the subtitle (from the account export), or Medium's summary text with the title it repeats removed |
| `tags`          | tag slugs (RSS categories, scraped tag links, or page state), after `tags.json` cleanup when present; always slugs -- `tags.json`'s `"display"` names them at render time, in the sites, not here |
| `images`        | relative paths of images used by the body |
| `body_source`   | `export` (account export), `feed` (RSS `content:encoded`), `page` (rendered HTML), `ghost` (Ghost page from a Wayback capture) or `state` (reconstructed from a shell page's embedded editor state) |"""

README_TEMPLATE = """\
# Medium archive of {base}

Generated by `medium-archive` and rewritten by every `convert` run, so
corrections to it belong in the tool rather than in this file. This
directory is a self-contained archive of the publication, intended to
support migrating the blog off Medium.

This file covers the archive itself: the downloaded sources, the
hand-written files that belong with them, and the two small derived
files worth keeping beside them. The bulky generated trees are
documented where they are generated -- `posts/README.md` for the
converted posts, `SITES.md` for the generated sites -- so a change in
how a post converts or how a site is built leaves this file alone.

* `raw/` is the **source of truth**: material downloaded from Medium,
  unmodified. `medium-archive fetch` produces it. Back it up. It is the
  only part that cannot be regenerated once the Medium site is gone.
* `posts.json` and `redirects.csv` are **derived**: `medium-archive
  convert` produces them, along with the `posts/` tree beside them, from
  `raw/` alone with no network access. They can be deleted and
  regenerated at any time (`convert --clean`). If the archive lives in
  version control, commit these two anyway: they are small and diffable,
  so a change to `fixups/` or `tags.json` shows its effect on every post
  in their diff, and `redirects.csv` is the contract the new site's
  redirects are built from. The bulky derived trees (`posts/` and the
  site directories) are better ignored and regenerated, together with
  the READMEs written inside them.
* `site.json` is **hand-written** and belongs with the archive. It
  holds the site-wide text every exporter reads (title, description,
  landing-page intro), the optional extras a site can carry, and
  `base_url`, the domain the site is served from. Every absolute URL a
  generated site bakes in comes from `base_url`, so set it before
  deploying and re-run the exporter (see `SITES.md`).
* `fixups/` (optional) holds **hand-written corrections** that `convert`
  and `compare` apply to the in-memory copy of raw files. Defects
  authored into the sources themselves, such as a broken href, a typo
  or a mangled paragraph, are fixed reproducibly while `raw/` stays
  byte-for-byte as fetched. `*.sub` files are single-line substitutions:
  a `file:` target, then `old:`/`new:` pairs, with an optional `count:`
  for the exact number of occurrences expected, `old-regex:` for a
  regex, and `#` comments. Prefer them, since raw HTML is often one
  enormous line that makes a unified diff unreadable. `*.patch` files
  are unified patches (targets named `<medium_id>/<file>`) for
  structural edits a substitution cannot express. A fixup that no longer
  applies aborts the run rather than being skipped. Back them up with
  `raw/`.
* `tags.json` (optional) holds **hand-written tag cleanup** that
  `convert` applies as it writes each post's front matter, so tags that
  only made sense on medium.com can be dropped and variants of one
  concept consolidated, reproducibly, while `raw/` keeps the original
  tags. `"drop"` lists tags to remove everywhere. `"rename"` maps an old
  tag to a new one; several variants renamed to one tag consolidate, and
  a post tagged with two variants gets the target once. `"imply"` maps a
  tag to the tags it entails everywhere it appears. `"add"` and
  `"remove"` put tags on, and take them off, specific posts by slug: for
  a topic the Medium tags never named, and for a tag that does not
  describe the post that inherited it. `"display"` gives a tag the name
  a site shows it under (`"ipython": "IPython"`); the tag stays a slug
  everywhere it is stored, named or built into a URL while the pages
  read correctly, and a tag with no entry shows as itself with its
  hyphens as spaces (`open-science` -> "open science"). `posts.json` and
  every derived site inherit the cleaned tags. An entry matching no post
  aborts a full `convert` run, like a fixup that no longer applies.
  `medium-archive stats --tags` lists every tag with its post count as
  the worklist for curating the file. Back it up with `raw/`.

## Layout

```
README.md                     this file
raw/
  index.json                  every archived post, keyed by its Medium URL
                                (or original URL for Ghost posts):
                                medium_id, title, published (from the page),
                                sitemap_date, found_via (feed/sitemap/
                                wayback/file/ghost-wayback), fetched_at,
                                images, in_feed, plus in_export/imported_at/
                                draft for posts merged from a Medium account
                                export, and in_ghost/ghost_url/
                                ghost_imported_at for posts with a Ghost
                                capture attached by `import-ghost`
  missing.json                posts that discovery (usually the Wayback
                                Machine) found but Medium no longer serves
                                (HTTP 404/410, or "soft-404": Medium's
                                not-found page served with status 200):
                                status, medium_id, found_via, approx_date
                                (first Wayback capture; an upper bound on
                                the publish date), wayback_url, checked_at,
                                plus same_slug_archived when the archive
                                holds the same slug under another id --
                                the post was likely deleted and republished.
                                Present only when such posts exist. Their
                                content survives only as web.archive.org
                                captures -- fetch does not recover it
                                automatically. Mangled variants of archived
                                URLs (truncated ids, stray hyphens) are
                                recognized and never flagged
  feed.xml                    the publication RSS feed as downloaded
  <medium_id>/                one directory per post (12-hex Medium id;
                                `ghost-<slug>` for posts recovered with
                                `import-ghost`)
    page.html                 the post page, byte-for-byte as served (for
                                Ghost posts: the Wayback capture)
    ghost.html                the post's Ghost capture, when `import-ghost`
                                found the post archived under both a Ghost
                                and a Medium URL; an alternate body source
                                alongside page.html, like export.html
    ghost.json                for any post with a Ghost source: original_url,
                                snapshot_timestamp, wayback_url, generator,
                                and the Ghost page's own title/published
                                (Medium migrations sometimes retitle posts
                                and shift dates)
    export.html               the post's file from a Medium account export,
                                when one was merged in with `import-export`;
                                the editor's own HTML, byte-for-byte
    feed_item.json            the post's RSS item, when the feed covered it
                                at fetch time (title, authors, tags, date,
                                content_html). Only ~10 recent posts have one.
    images.json               {{source_url: filename}} for images/
    images/<filename>         full-resolution images referenced by the post
    media/<media_id>.json     embed media resources the page's state leaves
                                unresolved (gist embeds, mostly): the
                                medium.com/media payload that names the
                                embed's target
    media/<media_id>.gist.json  the embedded gist's files, as returned by
                                the GitHub gists API; convert inlines them
                                as code fences (a Markdown file verbatim)
fixups/*.sub, *.patch         optional hand-written corrections, applied to
                                raw files in memory by convert and compare
tags.json                     optional hand-written tag cleanup ("drop",
                                "rename", "imply", "add", "remove") plus the
                                names tags display under ("display"), applied
                                by convert to front matter
site.json                     optional hand-written site settings read by
                                every site exporter: title, description,
                                intro (landing page), base_url, avatar,
                                favicon, announcement, image caps, hugo
posts.json                    converted posts, keyed by Medium URL; same
                                fields as each post's front matter plus `dir`
redirects.csv                 original_path, medium_id, original_url,
                                new_dir, date, title -- one row per post
posts/                        the converted posts, generated by convert;
                                described by posts/README.md
site-myst/,                   the generated sites, built from posts/ by the
site-hugo/,                     site exporters; described by SITES.md
site-pelican/
```

## Post fields (`posts.json`)

`posts.json` is keyed by Medium URL. Each entry carries the fields below
plus `dir`, the post's directory under `posts/`; the same fields make up
each converted post's front matter (see `posts/README.md`).

{fields}

## Redirects

`redirects.csv` has everything needed to map old Medium URLs to the new
site once its URL scheme is decided. Inbound links to Medium posts may use
the full slug+id path (`original_path`) or the short form
`/p/<medium_id>`, and both should be redirected. A post with a `ghost_url`
gets a second row for its Ghost path, so links from before the blog's
Medium era keep working too.

## Conventions and caveats

* Posts flagged in `raw/missing.json` are gone from Medium, deleted or
  unpublished. Each entry's `wayback_url` points at its web.archive.org
  captures for manual recovery. An entry with `same_slug_archived` was
  likely deleted and republished under a new id, and the archive already
  holds the replacement. A re-run of `fetch` re-checks flagged posts and
  unflags any that reappear.
* Posts recovered with `import-ghost` come from a Ghost blog via the
  Wayback Machine, not from Medium. Their `original_url` is the Ghost
  URL, `medium_id` is null, and their images come from Wayback captures
  too; an image with no capture keeps its original, likely dead, URL. A
  post archived from both platforms keeps the Medium page as its default
  body source with the Ghost capture attached. `compare --ghost` diffs
  the two conversions per post (Medium's importer often mangles code
  blocks), and `convert --prefer-ghost` converts from the Ghost source
  instead, at the cost of any edits made on Medium after the migration.
  Attached Ghost images are stored alongside the Medium ones with a `g`
  filename prefix.
* Tags, the updated date and the publication canonical URL come from the
  post page, so fetching remains worthwhile even when a Medium account
  export is available; the export contributes the exact first-publish
  timestamp and the untruncated subtitle. Which source each body is
  converted from is `body_source`, and the preference order behind it is
  documented in `posts/README.md`.
* Image filenames are `<NNN>-<original basename>`. The same asset
  served from `miro.medium.com` and `cdn-images-1.medium.com` is stored
  once. An image fetched from an extensionless URL is stored as `.bin`
  in `raw/`; the copies convert and the site exporters make carry the
  extension its bytes call for.

## Regenerating

    medium-archive fetch {base} --out .   # incremental; add new posts
    medium-archive compare --out .          # verify page vs export conversion
    medium-archive convert --clean --out .  # rebuild posts/ from raw/
    medium-archive lint --out .             # check for conversion defects
    medium-archive stats --out .            # summarize the archive

Building the generated sites is documented in `SITES.md`.
"""

POSTS_README_TEMPLATE = """\
# Converted posts

Generated by `medium-archive convert` from `../raw/` and rewritten by
every run, so corrections to it belong in the tool rather than in this
file. This directory is derived output: no network access goes into it,
and it can be deleted and rebuilt at any time (`convert --clean`). It is
the layer to change when adapting the archive to a new site generator.
The archive it is derived from -- the raw sources and the hand-written
files that correct them -- is documented in `../README.md`.

An archive in version control is usually better off ignoring this tree,
this file with it, and regenerating both; the small derived files
`../posts.json` and `../redirects.csv` are the ones worth committing.

## Layout

```
posts/
  README.md                   this file
  <YYYY-MM-DD>-<slug>/        one directory per converted post
    index.md                  front matter + Markdown body
    images/<filename>         full-resolution images copied from ../raw/,
                                referenced relatively
```

## Front matter (`index.md`)

The front matter block between `---` lines is JSON, which is valid YAML.
`../posts.json` carries the same fields for every post, plus `dir`.

{fields}

## Conventions and caveats

* Bodies are Markdown produced by markdownify from Medium HTML. Code
  blocks, lists and headings are generally fine, and fences carry the
  language Medium recorded for the block when any. Tables and embeds
  are not: iframes appear as `[embed: <url>]` links and need manual
  replacement. Gist embeds are the exception. Their code is inlined as
  fenced blocks from `../raw/<id>/media/`, where fetch archives the
  gist's files, and a Markdown gist file (a table, usually) is inlined
  verbatim so it renders as prose. A gist embed whose media was never
  archived converts to a `[missing embed: <name>]` placeholder (from
  the state or a feed body, which have no URL for it) or an
  `[embed: <gist url>]` link (from an export or Ghost body, which names
  the gist). `lint` flags the placeholders; re-run fetch to recover
  them.
* Medium boilerplate is stripped in `convert` and still present in
  `../raw/<id>/page.html`: "was originally published in ... on Medium",
  stat tracking pixels, clap/share UI, the author header.
* Body source preference is `export` > `state` > `feed` > `page`,
  overridden with `convert --prefer-page`. Export bodies are the Medium
  editor's own HTML and convert most faithfully. `state` is the same
  content as the editor stores it, read from the page's embedded state,
  and keeps what the rendered HTML destroys: the full text span of a
  link containing a code fragment, and iframe embeds an un-hydrated
  capture drops. `feed` is the RSS `<content:encoded>` body, which
  carries no `<code>` at all, demotes the authored heading levels (`##`
  arrives as `###`) and drops the section dividers, so it is used only
  for a capture whose page has no usable state; it is also the one body
  Medium truncates, on a member-only post. `page` is the rendered HTML,
  used when there is no other source. The export contributes the exact
  first-publish timestamp and the untruncated subtitle. `compare --state`
  verifies the state conversion against the export the way plain
  `compare` verifies the page conversion.
* Medium sometimes serves a post page as its bare application shell,
  with no server-rendered article at all. Even such captures convert:
  the embedded editor state carries the full paragraph list, title,
  timestamps, author and tags. Their images were never fetched, though,
  so those bodies keep remote miro.medium.com URLs until the post is
  re-fetched; `lint` reports each one.
* Posts recovered with `import-ghost` have a Ghost URL as their
  `original_url` and a null `medium_id`, and `convert --prefer-ghost`
  converts a post attached to both platforms from its Ghost capture
  instead of its Medium page.
* Links inside bodies that point at other posts in this publication
  still point at Medium. Rewrite them using `../redirects.csv` when
  migrating; the site exporters already do this for the sites they
  build.
* Image filenames are `<NNN>-<original basename>`, copied here from
  `../raw/`. An image the raw archive stored as `.bin` (fetched from an
  extensionless URL) is copied with the extension its bytes call for.

## Regenerating

From the archive root:

    medium-archive convert --clean --out .  # rebuild posts/ from raw/
    medium-archive lint --out .             # check for conversion defects
"""

SITES_README = """\
# Generated sites

Generated by `medium-archive` and rewritten by every `convert` run, so
corrections to it belong in the tool rather than in this file. It covers
the site directories built from the converted posts; the archive they
are built from is documented in `README.md`, and the posts themselves in
`posts/README.md`.

`site-myst/`, `site-hugo/` and `site-pelican/` are built by
`medium-archive myst`, `hugo` and `pelican` from `posts/` and
`posts.json`. They are disposable output rather than archive: delete and
rebuild them at will, and leave them out of version control, together
with this file. All three give the posts the same page URLs, rewrite
links between posts of the publication to those pages, and write their
own `redirects.csv` mapping every old inbound path to the page that
generator actually serves. The hugo and pelican sites are the preferred
targets and share one theme; the myst site is a simpler alternate. What
the sites contain and how they look belongs to the tool and is
documented in the medium-archive README, so this file does not go stale
when a theme gains a feature.

The site-wide text and settings all three read come from the archive's
hand-written `site.json` (see `README.md`).

## Layout

```
site-myst/                    optional MyST site built by `medium-archive
                                myst` from posts/ + posts.json:
  myst.yml                    project config, plugins, and year-grouped toc
  index.md                    landing page: intro + cover-image post gallery
  archive.md                  chronological post list, grouped by year
  listing-covers.mjs          generated myst-listing companion plugin: makes
                                the gallery serve the local cover thumbnails
  posts/<YYYY-MM-DD>-<slug>/
    <page>.md                 the post, MyST front matter + rewritten body;
                                the page's URL slug is the filename, capped
                                by mystmd at 50 characters
    images/<filename>         display copies of the images in posts/ (see
                                the medium-archive README), plus the baked
                                cover.jpg gallery thumbnail
  redirects.csv               old inbound path -> the page URL mystmd serves
site-hugo/,                   optional Hugo/Pelican sites built by
site-pelican/                   `medium-archive hugo|pelican`: the same
                                posts as content/posts/<slug>/index.md with
                                generator-native front matter, config, and
                                the shared card-grid theme; each carries
                                its own redirects.csv
  data/tags.json,               the names tags and authors are shown under
  data/authornames.json,        and the profile address of each byline:
  data/authors.json             the same three files in both sites, read
                                by Hugo through hugo.Data and by the
                                pelican config beside them. Written from
                                the archive, and editable by hand in a
                                site kept under version control
```

## Conventions and caveats

* The images beside each page are display copies, capped per `site.json`
  (the full-resolution originals stay in `raw/` and `posts/`). A copy
  written in another format carries the extension its bytes call for.
* In `site-myst/` pages, `@handle` mentions and `$` signs are
  backslash-escaped so MyST does not parse them as citations or math.
  Links to in-page anchors that never survived the Medium conversion
  (old footnote anchors) stay as they are in `posts/` and are reported
  by `myst build`.
* Each site's `redirects.csv` is the generator's own: it maps the old
  inbound paths of the archive's `redirects.csv` to the page URLs that
  generator actually serves.
* The `data/*.json` files in `site-hugo/` and `site-pelican/` are
  derived from the archive like everything else in those directories,
  so an exporter run overwrites them. A tag or author name belongs in
  the archive's `tags.json` or in the post's byline; editing the data
  file directly is for a site kept as a checked-in project of its own.

## Building the sites

Tools: Hugo extended (0.156 or newer: the theme is written in the
layout structure Hugo looks pages up in today, and reads its data
files through `hugo.Data`; validated with 0.165),
`pip install pelican markdown-it-py mdit-py-plugins pyyaml pillow`,
`npm install -g mystmd pagefind`,
and optionally gifsicle (without it, animated-gif display copies keep
their full size).

Before deploying, set `base_url` in `site.json` to the site's real
domain (e.g. `"base_url": "https://blog.example.com"`) and re-run the
exporter step. Every absolute URL a generated site bakes in is built
from it.

hugo (preferred):

    medium-archive hugo --out .
    cd site-hugo
    hugo
    pagefind --site public
    python -m http.server -d public

pelican (preferred):

    medium-archive pelican --out .
    cd site-pelican
    pelican
    pagefind --site output
    pelican -l

myst:

    medium-archive myst --out .
    cd site-myst
    myst start
"""


def write_if_changed(path: Path, text: str):
    """Write the file, unless it already holds exactly this text. These
    documents are rewritten by every run and a run usually has nothing
    new to say, so rewriting the same bytes would touch the mtime of a
    committed file for nothing -- and every tool that reads mtimes, from
    a build to an rsync, would believe the file had changed."""
    data = text.encode("utf-8")
    if path.exists() and path.read_bytes() == data:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def write_readme(out: Path, base: str):
    """The archive README: the committed layer, and nothing else."""
    # The commands are written to run from the archive root, not with
    # the --out path of whichever run wrote this file: a path that moved
    # with the caller's working directory would churn the archive's diff
    # from one run to the next. The generation date is left out for the
    # same reason -- it changed the file on every run without saying
    # anything a re-run had changed.
    write_if_changed(out / "README.md", README_TEMPLATE.format(
        base=base.rstrip("/"),
        fields=FIELDS_TABLE,
    ))


def write_posts_readme(out: Path):
    """The README of the converted posts, inside the tree it describes."""
    write_if_changed(out / "posts" / "README.md",
                     POSTS_README_TEMPLATE.format(fields=FIELDS_TABLE))


def write_sites_readme(out: Path):
    """The README of the generated sites. One file for the three of
    them: they share their inputs, their page URLs and their theme, and
    a reader choosing between them wants them side by side."""
    write_if_changed(out / "SITES.md", SITES_README)
