"""The README files written into an archive.

Two generated documents, split by what each describes and by how often
that changes:

* ``archive/README.md`` covers the archive proper: ``raw/``, the
  hand-written files beside it, and the two small derived files worth
  committing with them. ``fetch``, ``import-ghost`` and ``convert`` write it.
* ``archive/posts/README.md`` covers the converted posts, and lives inside
  the tree it describes.

A project in version control commits the first and ignores the tree the
second describes, along with that file. Keeping the converted posts out
of the archive README is what lets a change in how a post converts leave
the one committed README alone. The generated sites document
themselves: every exporter writes a README into the site it builds,
where that site's own layout and build belong.
"""

from pathlib import Path

# The post fields, documented once and rendered into both the archive
# README (which describes posts.json) and the posts README (which
# describes the front matter of the same posts). Passed to str.format
# as an argument, so its braces need no escaping.
FIELDS_TABLE = """\
| field           | meaning |
|-----------------|---------|
| `title`         | post title; one Medium truncated from the opening heading is completed from it |
| `subtitle`      | the subtitle line as inline Markdown, or "" |
| `authors`       | list of `{"name", "url"}`; `url` is the Medium profile or null |
| `date`          | publish timestamp (ISO 8601, UTC) |
| `updated`       | last-modified timestamp, if known |
| `original_url`  | canonical Medium URL |
| `original_path` | path of `original_url` |
| `medium_id`     | Medium's hex post id (Medium also serves `/p/<id>`); null for Ghost-only posts |
| `slug`          | `original_path` without the id suffix, percent-decoded |
| `canonical_url` | a different canonical URL the post declared (e.g. a story imported from elsewhere), or null |
| `ghost_url`     | the post's Ghost-era URL when a capture is attached, or null |
| `description`   | plain-text summary, without the repeated title; completed from `subtitle` where Medium truncated it |
| `tags`          | tag slugs, after `tags.json` cleanup |
| `images`        | relative paths of images used by the body |
| `body_source`   | `export`, `state` (embedded editor state), `feed` (RSS body), `page` (rendered HTML) or `ghost` |"""

README_TEMPLATE = """\
# Medium archive of {base}

Generated by `medium-archive`; rewritten by `fetch`, `import-ghost` and
`convert`. The converted posts are described in `posts/README.md`, and
each generated site has its own README.

* `raw/`: material downloaded from Medium, unmodified. The only part
  that cannot be regenerated; back it up.
* `posts.json`, `redirects.csv`, `posts/`: derived from `raw/` by
  `convert`, offline (`convert --clean` rebuilds them). Commit the two
  files, whose diffs show the effect of a fixup or tag change; ignore
  `posts/`.
* `fixups/` (optional, hand-written): corrections applied to raw files
  in memory by `convert` and `compare`. `*.sub` files hold a `file:`
  line and `old:`/`new:` pairs (optional `count:`, `old-regex:`, `#`
  comments); `*.patch` files are unified diffs with targets named
  `<medium_id>/<file>`. A fixup that no longer applies aborts the run.
* `tags.json` (optional, hand-written): tag cleanup applied by
  `convert`: `"drop"` (remove everywhere), `"rename"` (old -> new),
  `"imply"` (tag -> tags it entails), `"add"`/`"remove"` (slug -> tags),
  `"display"` (tag -> name shown by the sites; unset, hyphens become
  spaces). An entry that changes no post aborts a full run. `stats
  --tags` lists every tag with its count.
* `../site/site.toml` (hand-written): site settings and images read by
  the exporters. Set `base_url` before deploying.

## Layout

```
raw/
  index.json                  every archived post, keyed by URL: medium_id,
                                title, published, sitemap_date, found_via,
                                fetched_at, images, in_feed; in_export,
                                imported_at, draft (import-export); in_ghost,
                                ghost_url, ghost_imported_at (import-ghost);
                                page_blocked (page refused by a bot wall,
                                archived from the RSS body; fetch retries it)
  missing.json                discovered posts Medium no longer serves:
                                status, medium_id, found_via, approx_date,
                                wayback_url, checked_at, same_slug_archived
  feed.xml                    the RSS feed
  <medium_id>/                one per post (`ghost-<slug>` for Ghost-only posts)
    page.html                 the post page as served (Ghost: the capture)
    export.html               the account-export file (import-export)
    ghost.html                the Ghost capture of a post also on Medium
    ghost.json                Ghost source: original_url, snapshot_timestamp,
                                wayback_url, generator, title, published
    feed_item.json            the RSS item, if the feed had the post
    images.json               {{source_url: filename}}
    images/<NNN>-<name>       full-resolution images (`g` prefix: from Ghost)
    media/<id>.json           medium.com/media payload for an embed
    media/<id>.gist.json      a gist's files (GitHub API)
    media/tweet-<id>.json     a tweet's oEmbed payload, or {{"deleted": true}}
    media/tweet-<id>.media.json  a tweet's photos (X syndication)
    media/carbon-<id>.json    a Carbon snippet's code and language
fixups/                       optional corrections
tags.json                     optional tag cleanup
posts.json                    converted posts keyed by URL: the fields below plus `dir`
redirects.csv                 original_path, medium_id, original_url, new_dir,
                                date, title; a second row for a `ghost_url`
posts/                        converted posts (git-ignored)
```

## Post fields (`posts.json`)

{fields}

## Notes

* `raw/missing.json` entries survive only on web.archive.org; recover
  them by hand from `wayback_url`. `same_slug_archived` means the post
  was probably republished under a new id. `fetch` re-checks them.
* Ghost-only posts have the Ghost URL as `original_url` and a null
  `medium_id`; their images come from Wayback captures, and an image
  with no capture keeps its original URL.
* An image fetched from an extensionless URL is stored as `.bin`; the
  converted and site copies get the right extension.

## Regenerating

From the project root:

    medium-archive fetch {base}
    medium-archive compare
    medium-archive convert --clean
    medium-archive lint
    medium-archive stats
"""

POSTS_README_TEMPLATE = """\
# Converted posts

Generated by `medium-archive convert` from `../raw/`, offline, and
rewritten by every run. Can be deleted and rebuilt (`convert --clean`).
The archive is described in `../README.md`.

## Layout

```
<YYYY-MM-DD>-<slug>/
  index.md                    front matter + Markdown body
  images/<NNN>-<name>         full-resolution images from ../raw/
```

## Front matter (`index.md`)

JSON between `---` lines (valid YAML); `../posts.json` has the same
fields plus `dir`.

{fields}

## Body source preference

`export` > `state` > `feed` > `page`; `convert --prefer-page` forces
`page`, `convert --prefer-ghost` uses an attached Ghost capture.

* `export`: the Medium editor's HTML from an account export; the most
  faithful.
* `state`: the editor state embedded in the page; keeps link text and
  embeds the rendered HTML loses, and converts shell-only captures
  (whose images keep remote URLs until re-fetched).
* `feed`: the RSS body; no inline code, demoted headings, no dividers,
  truncated for member-only posts.
* `page`: the rendered HTML.

`compare` and `compare --state` check the `page` and `state`
conversions against exports.

## Conversion notes

* Bodies are converted with markdownify. Medium chrome is removed; it
  remains in `../raw/`.
* The repeated title is removed. The subtitle is moved to `subtitle`.
* Gists are inlined, tweets become blockquotes, Carbon snippets become
  code blocks, Giphy media are served locally, and YouTube, Vimeo,
  CodePen, Spotify and SoundCloud stay `<iframe>` players. Other embeds
  become `[embed: <url>]` links. Embed media not yet fetched appear as
  links or `[missing embed: <name>]` placeholders; `lint` reports them.
* Links to other posts of the publication still point at Medium; the
  site exporters rewrite them using `../redirects.csv`.

## Regenerating

From the project root:

    medium-archive convert --clean
    medium-archive lint
"""

def write_if_changed(path: Path, text: str):
    """Write the file, unless it already holds exactly this text. These
    documents are rewritten by every run and a run usually has nothing
    new to say, so rewriting the same bytes would touch the mtime of a
    committed file for nothing -- and every tool that reads mtimes, from
    a build to an rsync, would believe the file had changed."""
    data = text.encode("utf-8")
    if path.exists() and path.read_bytes() == data:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def write_readme(archive: Path, base: str):
    """The archive README: the committed layer, and nothing else."""
    # The commands are written to run from the project root, not with
    # the --out path of whichever run wrote this file: a path that moved
    # with the caller's working directory would churn the archive's diff
    # from one run to the next. The generation date is left out for the
    # same reason -- it changed the file on every run without saying
    # anything a re-run had changed.
    write_if_changed(archive / "README.md", README_TEMPLATE.format(
        base=base.rstrip("/"),
        fields=FIELDS_TABLE,
    ))


def write_posts_readme(archive: Path):
    """The README of the converted posts, inside the tree it describes."""
    write_if_changed(archive / "posts" / "README.md",
                     POSTS_README_TEMPLATE.format(fields=FIELDS_TABLE))
