"""The zola step: build a Zola site in <out>/site-zola/ from the
converted archive. Same reproducibility contract as the myst step (see
sites.py); render with `zola serve` or `zola build` inside
<out>/site-zola/ (https://www.getzola.org).

Each post becomes content/posts/<stem>/index.md with its images beside
it (Zola colocation), so the directory name is the page URL
(/posts/<stem>/). Front matter is TOML: tags and authors feed Zola's
taxonomies -- per-term listing pages and per-term Atom feeds are built
in, as are the site feed (atom.xml) and a full-text search index -- the
exporter's templates wire it to a search box in the page header, so
search works out of the box. Old inbound paths become aliases, so Zola emits
redirect stubs for old links on any static host. The exporter writes a
small self-contained set of Tera templates; replace them without
touching content/.
"""

import json
import sys

from .sites import (clean_site, export_content, load_site_inputs, old_paths,
                    page_stems, write_redirects_csv)

CONFIG = """\
# Generated by `medium-archive zola`; do not edit.
# Site title/description/intro come from <out>/site.json.
base_url = {base_url}
title = {title}
description = {description}
generate_feeds = true
feed_filenames = ["atom.xml"]
# a feed announces new posts; the site itself is the archive
feed_limit = 20
build_search_index = true

taxonomies = [
    {{ name = "tags", feed = true }},
    {{ name = "authors", feed = true }},
]

[link_checker]
# old posts carry in-page anchor links whose anchors never survived the
# original Medium conversion; report them without failing the build
internal_level = "warn"

[markdown]
highlight_code = true
"""

BASE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title %}{{ config.title }}{% endblock %}</title>
<meta name="description" content="{{ config.description }}">
<link rel="alternate" type="application/atom+xml" href="{{ get_url(path="atom.xml") | safe }}" title="{{ config.title }}">
<link rel="stylesheet" href="{{ get_url(path="css/style.css") | safe }}">
</head>
<body>
<header><nav>
<a class="site" href="{{ config.base_url | safe }}">{{ config.title }}</a>
<a href="{{ get_url(path="/tags") | safe }}">Tags</a>
<a href="{{ get_url(path="/authors") | safe }}">Authors</a>
<a href="{{ get_url(path="atom.xml") | safe }}">RSS</a>
<span class="search-box"><input id="search" type="search" placeholder="Search…" autocomplete="off">
<div id="search-results"></div></span>
</nav></header>
<main>
{% block content %}{% endblock %}
</main>
<script src="{{ get_url(path="elasticlunr.min.js") | safe }}"></script>
<script>
(function () {
  var input = document.getElementById("search");
  var results = document.getElementById("search-results");
  var index = null;
  input.addEventListener("focus", function () {
    if (index !== null) return;
    index = false;                       // loading
    var s = document.createElement("script");
    s.src = "{{ get_url(path="search_index.en.js") | safe }}";
    s.onload = function () { index = elasticlunr.Index.load(window.searchIndex); };
    document.head.appendChild(s);
  });
  input.addEventListener("input", function () {
    if (!index || input.value.length < 2) { results.innerHTML = ""; return; }
    var hits = index.search(input.value, {
      bool: "AND", expand: true,
      fields: { title: { boost: 2 }, body: { boost: 1 } },
    }).slice(0, 10);
    results.innerHTML = "";
    hits.forEach(function (h) {
      var a = document.createElement("a");
      a.href = h.ref;
      a.textContent = index.documentStore.getDoc(h.ref).title || h.ref;
      results.appendChild(a);
    });
  });
  document.addEventListener("click", function (e) {
    if (!e.target.closest(".search-box")) results.innerHTML = "";
  });
})();
</script>
</body>
</html>
"""

INDEX = """\
{% extends "base.html" %}
{% block content %}
<h1>{{ config.title }}</h1>
{{ section.content | safe }}
{% set posts = get_section(path="posts/_index.md") %}
{% for year, pages in posts.pages | group_by(attribute="year") %}
<h2>{{ year }}</h2>
<ul class="post-list">
{% for page in pages %}<li><time>{{ page.date }}</time> <a href="{{ page.permalink | safe }}">{{ page.title }}</a>{% if page.taxonomies.authors %} · {{ page.taxonomies.authors | join(sep=", ") }}{% endif %}</li>
{% endfor %}</ul>
{% endfor %}
{% endblock %}
"""

PAGE = """\
{% extends "base.html" %}
{% block title %}{{ page.title }} · {{ config.title }}{% endblock %}
{% block content %}
<article>
<h1>{{ page.title }}</h1>
<p class="meta">{% if page.date %}<time>{{ page.date }}</time>{% endif %}{% for a in page.taxonomies.authors | default(value=[]) %} · <a href="{{ get_taxonomy_url(kind="authors", name=a) | safe }}">{{ a }}</a>{% endfor %}</p>
{{ page.content | safe }}
{% if page.taxonomies.tags %}<p class="tags">{% for t in page.taxonomies.tags %}<a href="{{ get_taxonomy_url(kind="tags", name=t) | safe }}">#{{ t }}</a> {% endfor %}</p>{% endif %}
</article>
{% endblock %}
"""

SECTION = """\
{% extends "base.html" %}
{% block title %}{{ section.title }} · {{ config.title }}{% endblock %}
{% block content %}
<h1>{{ section.title }}</h1>
<ul class="post-list">
{% for page in section.pages %}<li><time>{{ page.date }}</time> <a href="{{ page.permalink | safe }}">{{ page.title }}</a></li>
{% endfor %}</ul>
{% endblock %}
"""

TAXONOMY_LIST = """\
{% extends "base.html" %}
{% block title %}{{ taxonomy.name }} · {{ config.title }}{% endblock %}
{% block content %}
<h1>{{ taxonomy.name }}</h1>
<ul class="term-list">
{% for term in terms %}<li><a href="{{ term.permalink | safe }}">{{ term.name }}</a> ({{ term.pages | length }})</li>
{% endfor %}</ul>
{% endblock %}
"""

TAXONOMY_SINGLE = """\
{% extends "base.html" %}
{% block title %}{{ term.name }} · {{ config.title }}{% endblock %}
{% block content %}
<h1>{{ term.name }}</h1>
<ul class="post-list">
{% for page in term.pages %}<li><time>{{ page.date }}</time> <a href="{{ page.permalink | safe }}">{{ page.title }}</a></li>
{% endfor %}</ul>
{% endblock %}
"""

POSTS_SECTION = """\
+++
title = "Posts"
sort_by = "date"
template = "section.html"
+++
"""


def front_matter(url: str, post: dict, stem: str) -> str:
    """TOML front matter; strings via JSON, whose escapes TOML shares."""
    j = lambda v: json.dumps(v, ensure_ascii=False)
    # explicit slug: Zola strips a leading YYYY-MM-DD- from the directory
    # name, which would collide the date-disambiguated duplicate slugs
    lines = ["+++", f"title = {j(post['title'])}", f"slug = {j(stem)}"]
    if post.get("description"):
        lines.append(f"description = {j(post['description'])}")
    if post.get("date"):
        lines.append(f"date = {post['date']}")       # TOML datetime, unquoted
    if post.get("updated"):
        lines.append(f"updated = {post['updated']}")
    lines.append(f"aliases = {j([p for p, _ in old_paths(post, url)])}")
    lines.append("[taxonomies]")
    if post.get("tags"):
        lines.append(f"tags = {j(post['tags'])}")
    if post.get("author"):
        lines.append(f"authors = {j([post['author']])}")
    return "\n".join(lines) + "\n+++\n\n"


def build_site(out):
    manifest, config = load_site_inputs(out)
    stems = page_stems(manifest)
    site = out / "site-zola"
    clean_site(site, keep=("public",))

    (site / "content" / "posts").mkdir(parents=True)
    (site / "content" / "_index.md").write_text(
        "+++\n+++\n\n" + (config.get("intro", "") + "\n"
                          if config.get("intro") else ""), encoding="utf-8")
    (site / "content" / "posts" / "_index.md").write_text(POSTS_SECTION,
                                                          encoding="utf-8")
    pages = export_content(out, site, manifest, stems,
                           lambda url, p: front_matter(url, p, stems[url]))

    (site / "config.toml").write_text(CONFIG.format(
        base_url=json.dumps(config.get("base_url", "https://example.org")
                            .rstrip("/")),
        title=json.dumps(config["title"], ensure_ascii=False),
        description=json.dumps(config.get("description", ""),
                               ensure_ascii=False),
    ), encoding="utf-8")
    for rel, text in {"templates/base.html": BASE,
                      "templates/index.html": INDEX,
                      "templates/page.html": PAGE,
                      "templates/section.html": SECTION,
                      "templates/taxonomy_list.html": TAXONOMY_LIST,
                      "templates/taxonomy_single.html": TAXONOMY_SINGLE,
                      "static/css/style.css": _css()}.items():
        path = site / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    write_redirects_csv(site, manifest, stems, lambda stem: f"/posts/{stem}/")
    print(f"zola done: {pages}/{len(manifest)} pages -> {site}", file=sys.stderr)
    print(f"render it with: cd {site} && zola serve   (or: zola build)",
          file=sys.stderr)
    return site


CSS = """\
body { max-width: 46rem; margin: 0 auto; padding: 0 1rem 4rem;
       font: 1.05rem/1.6 system-ui, sans-serif; color: #222; }
header nav { padding: 1rem 0; border-bottom: 1px solid #ddd; }
header nav a { margin-right: 1rem; color: #555; text-decoration: none; }
header nav a.site { font-weight: 700; color: #222; }
a { color: #0a67a3; }
img { max-width: 100%; height: auto; }
pre { overflow-x: auto; padding: .8rem; background: #f6f6f6; }
code { background: #f6f6f6; }
blockquote { margin-left: 0; padding-left: 1rem; border-left: 3px solid #ddd; color: #555; }
.post-list { list-style: none; padding: 0; }
.post-list time, .meta time { color: #777; font-variant-numeric: tabular-nums; }
.meta, .tags { color: #777; }
figcaption, em img + em { color: #777; }
"""

SEARCH_CSS = """\
.search-box { position: relative; float: right; }
.search-box input { font: inherit; padding: .1rem .4rem; }
#search-results { position: absolute; right: 0; z-index: 1; min-width: 20rem;
                  background: #fff; border: 1px solid #ddd; }
#search-results:empty { display: none; }
#search-results a { display: block; padding: .3rem .6rem; text-decoration: none; }
#search-results a:hover { background: #f0f0f0; }
"""


def _css() -> str:
    return CSS + SEARCH_CSS


def cmd_zola(args):
    build_site(args.out)
