# Generated by `medium-archive pelican` and rewritten on every export;
# edit site.toml and data/*.yaml instead.

import datetime as _datetime
import os as _os
import tomllib as _tomllib

import yaml as _yaml

_HERE = _os.path.dirname(_os.path.abspath(__file__))


def _site():
    """site.toml beside this config. It is required: a missing file is
    an error, not defaults."""
    with open(_os.path.join(_HERE, "site.toml"), "rb") as fh:
        return _tomllib.load(fh)


_SITE = _site()

# --------------------------------------------------------------- the site
# One setting per site.toml key (documented there); only title is
# required.
SITENAME = _SITE["title"]
SITESUBTITLE = _SITE.get("description") or ""
SITEURL = (_SITE.get("base_url") or "").rstrip("/")
DEFAULT_LANG = _SITE.get("locale") or "en"
AVATAR = _SITE.get("avatar")
FAVICON = _SITE.get("favicon")
LOGO = _SITE.get("logo")
LOGO_DARK = _SITE.get("logo_dark")
LOGO_LINK = _SITE.get("logo_link")
ANNOUNCEMENT = _SITE.get("announcement")
# Markdown; rendered to INTRO and FOOTER at the end of this file, once
# the reader's parser is defined
_INTRO_MD = _SITE.get("intro")
_FOOTER_MD = _SITE.get("footer")
NOINDEX = bool(_SITE.get("noindex"))
# "stubs", "file", "both" or "none", split into the plugin's two switches
_REDIRECTS = _SITE.get("redirects") or "both"
REDIRECT_STUBS = _REDIRECTS in ("both", "stubs")
REDIRECT_FILE = _REDIRECTS in ("both", "file")
TWITTER = _SITE.get("twitter")
PROFILES = _SITE.get("profiles") or []
NEWSLETTER = _SITE.get("newsletter")
PLAUSIBLE = _SITE.get("plausible")
SHARE_IMAGE = _SITE.get("share_image")
SHARE_IMAGE_SIZE = _SITE.get("share_image_size")
COVER_SIZE = _SITE.get("cover_size")

# ---------------------------------------------------------------- reading
# Keep the date format in sync with the hugo theme's card partial.
TIMEZONE = "UTC"
DEFAULT_DATE_FORMAT = "%B %d, %Y"

# Front-matter fields rendered as Markdown; article.html outputs
# subtitle as HTML.
FORMATTED_FIELDS = ["summary", "subtitle"]

# Autoescape on: titles, tag and author names are plain text from the
# archived posts and must not be emitted raw. The theme marks the values
# that really are HTML with |safe. This setting replaces pelican's
# default rather than merging with it, so its other keys are restated.
JINJA_ENVIRONMENT = {
    "autoescape": True,
    "trim_blocks": True,
    "lstrip_blocks": True,
    "extensions": [],
}

# ------------------------------------------------------- pages and URLs
PATH = "content"
THEME = "theme"
ARTICLE_PATHS = ["posts"]
STATIC_PATHS = ["posts"]        # colocated images, placed via {attach}
PAGE_PATHS = []
# Posts live at content/posts/<year>/<slug>/index.md. The directory name
# is the default slug, taken as is (not slugified); a `slug:` in front
# matter overrides it. The URL's year comes from the post's `date:`, not
# the directory. The site plugin reports posts whose directory name or
# year differs from the URL, and stops the build if two share a URL.
PATH_METADATA = r"posts/(?P<diryear>\d{4})/(?P<slug>[^/]+)/"
ARTICLE_URL = "posts/{date:%Y}/{slug}/"
ARTICLE_SAVE_AS = "posts/{date:%Y}/{slug}/index.html"
# year pages only (period_archives.html); URLs have no month or day
YEAR_ARCHIVE_URL = "posts/{date:%Y}/"
YEAR_ARCHIVE_SAVE_AS = "posts/{date:%Y}/index.html"
TAG_URL = "tags/{slug}/"
TAG_SAVE_AS = "tags/{slug}/index.html"
TAGS_URL = "tags/"
TAGS_SAVE_AS = "tags/index.html"
AUTHOR_URL = "authors/{slug}/"
AUTHOR_SAVE_AS = "authors/{slug}/index.html"
AUTHORS_URL = "authors/"
AUTHORS_SAVE_AS = "authors/index.html"
ARCHIVES_URL = "archives/"
ARCHIVES_SAVE_AS = "archives/index.html"
PAGINATION_PATTERNS = (
    (1, "{url}", "{save_as}"),
    (2, "{base_name}/page/{number}/", "{base_name}/page/{number}/index.html"),
)
DEFAULT_PAGINATION = 24
DEFAULT_CATEGORY = "posts"
SLUGIFY_SOURCE = "basename"     # fallback for posts outside PATH_METADATA
DIRECT_TEMPLATES = ["index", "tags", "authors", "archives"]
TEMPLATE_PAGES = {"search.html": "search/index.html"}
CATEGORY_URL = ""               # categories are unused
CATEGORY_SAVE_AS = ""

# ------------------------------------------------------------- data files
_DATA_DIR = _os.path.join(_HERE, "data")


def _data(name):
    """A data/*.yaml file as a dict; a missing file reads as empty."""
    try:
        with open(_os.path.join(_DATA_DIR, name), encoding="utf-8") as fh:
            return _yaml.safe_load(fh) or {}
    except FileNotFoundError:
        return {}


def _authors(entries):
    """data/authors.yaml as (slug -> name, slug -> profile URL). Entries
    without a name or url are left out of that map."""
    names, links = {}, {}
    for slug, entry in entries.items():
        entry = entry or {}
        if entry.get("name"):
            names[slug] = entry["name"]
        if entry.get("url"):
            links[slug] = entry["url"]
    return names, links


# Tags and bylines reach Pelican as slugs, so their URLs are exact; the
# site plugin sets each Tag and Author object's display name from these
# maps. AUTHOR_LINKS is the Person's sameAs in the structured data.
TAG_DISPLAY = _data("tags.yaml")
AUTHOR_DISPLAY, AUTHOR_LINKS = _authors(_data("authors.yaml"))

FEED_ALL_ATOM = "feeds/all.atom.xml"
FEED_MAX_ITEMS = 20
CATEGORY_FEED_ATOM = None
TAG_FEED_ATOM = "feeds/tag-{slug}.atom.xml"
AUTHOR_FEED_ATOM = "feeds/author-{slug}.atom.xml"
AUTHOR_FEED_RSS = None

# ------------------------------------------------------------------ reader
# Markdown is read as CommonMark with markdown-it-py (`pip install
# markdown-it-py mdit-py-plugins`), replacing pelican's python-markdown
# reader.
import re as _re
import shlex as _shlex
import unicodedata as _unicodedata

from markdown_it import MarkdownIt as _MarkdownIt
from markdown_it.rules_core.replacements import RARE_RE as _RARE_RE
from markdown_it.rules_core.replacements import (
    replace_rare as _replace_rare)
from mdit_py_plugins.anchors import anchors_plugin as _anchors
from mdit_py_plugins.container import container_plugin as _container
from mdit_py_plugins.deflist import deflist_plugin as _deflist
from mdit_py_plugins.footnote import footnote_plugin as _footnote
from pygments import highlight as _highlight
from pygments.formatters.html import HtmlFormatter as _HtmlFormatter
from pygments.lexers import get_lexer_by_name as _lexer_by_name
from pygments.lexers import guess_lexer as _guess_lexer
from pygments.lexers.special import TextLexer as _TextLexer
from pygments.util import ClassNotFound as _ClassNotFound

# pelican's link placeholders. markdown-it percent-encodes the braces,
# so they are restored before pelican resolves them.
_PLACEHOLDERS = ("attach", "static", "filename", "tag", "author",
                 "category", "index")


def _keep_placeholders(url):
    for name in _PLACEHOLDERS:
        url = url.replace("%7B" + name + "%7D", "{" + name + "}")
    return url


def _slug(text):
    """A heading id, slugified as python-markdown's toc extension did so
    that existing anchors keep working."""
    text = _unicodedata.normalize("NFKD", text)
    text = text.encode("ascii", "ignore").decode("ascii")
    text = _re.sub(r"[^\w\s-]", "", text).strip().lower()
    return _re.sub(r"[-\s]+", "-", text)


def _attr(value):
    """Escape a double-quoted attribute value. ">" is escaped too: a raw
    one ends the tag early for regex readers such as pelican's {attach}
    resolution, which then leaves the image broken."""
    return (value.replace("&", "&amp;").replace('"', "&quot;")
            .replace("<", "&lt;").replace(">", "&gt;"))


def _body_image(src, alt="", link=None):
    """A lazily loaded <img> for the post body, marked with
    BODY_IMAGE_ATTR (defined in the site plugin section below) so the
    plugin's post-build pass can tell it from theme images. That pass
    also matches the literal loading="lazy" written here."""
    img = (f'<img alt="{_attr(alt)}" src="{src}" loading="lazy"'
           f' {BODY_IMAGE_ATTR}="">')
    return f'<a href="{_attr(link)}">{img}</a>' if link else img


_FRONT_MATTER_RE = _re.compile(r"\A---\r?\n(.*?)^(?:---|\.\.\.)\r?\n",
                               _re.MULTILINE | _re.DOTALL)


def _split_front_matter(text):
    """(YAML front matter, body). Without a `---` fence it is all body."""
    match = _FRONT_MATTER_RE.match(text)
    if not match:
        return "", text
    return match.group(1), text[match.end():]


def _replacements(state):
    """markdown-it's typographic replacements without the (c)/(tm)/(r)
    symbols, so "501(c)(3)" is left alone (the hugo site's Goldmark
    typographer does not substitute them either)."""
    if not state.md.options.typographer:
        return
    for token in state.tokens:
        if token.type == "inline" and token.children:
            if _RARE_RE.search(token.content):
                _replace_rare(token.children)


def _figure(md):
    """The exporter's `::: figure src="..." alt="..." link="..."`
    directive, rendered as <figure>/<figcaption>. The body is the
    caption, parsed as Markdown with its paragraph wrapper dropped."""
    def render(self, tokens, idx, options, env):
        token = tokens[idx]
        if token.nesting == -1:
            return "</figcaption>\n</figure>\n"
        args = dict(a.split("=", 1)
                    for a in _shlex.split(token.info)[1:] if "=" in a)
        for inner in tokens[idx + 1:]:
            if inner.type == "container_figure_close":
                break
            if inner.type in ("paragraph_open", "paragraph_close"):
                inner.hidden = True
        img = _body_image(args.get("src", ""), args.get("alt", ""),
                          args.get("link"))
        return f"<figure>\n{img}\n<figcaption>"

    md.use(_container, "figure", render=render)


def _make_md():
    # Tables, strikethrough and the typographer (smart quotes, dashes,
    # ellipses) match the hugo site's Goldmark settings; code is not
    # affected.
    md = _MarkdownIt("commonmark", {"xhtmlOut": False, "typographer": True})
    md.enable(["table", "strikethrough", "smartquotes", "replacements"])
    md.core.ruler.at("replacements", _replacements)
    md.use(_footnote).use(_deflist).use(_figure)
    # heading ids give search results per-section anchors
    md.use(_anchors, max_level=6, slug_func=_slug)

    def fence(self, tokens, idx, options, env):
        token = tokens[idx]
        try:
            lexer = (_lexer_by_name(token.info.split()[0]) if token.info
                     else _guess_lexer(token.content))
        except (_ClassNotFound, IndexError):
            lexer = _TextLexer()
        # the class the shared theme CSS styles, as hugo's chroma emits
        return _highlight(token.content, lexer,
                          _HtmlFormatter(cssclass="highlight", wrapcode=True))

    def image(self, tokens, idx, options, env):
        token = tokens[idx]
        token.attrSet("src", _keep_placeholders(token.attrGet("src") or ""))
        token.attrSet("loading", "lazy")
        token.attrSet(BODY_IMAGE_ATTR, "")
        return self.image(tokens, idx, options, env)

    def link_open(self, tokens, idx, options, env):
        token = tokens[idx]
        token.attrSet("href", _keep_placeholders(token.attrGet("href") or ""))
        return self.renderToken(tokens, idx, options, env)

    md.add_render_rule("fence", fence)
    md.add_render_rule("image", image)
    md.add_render_rule("link_open", link_open)
    return md


def _reader_class():
    """The reader class, built on first use so this config can be
    imported without pelican installed."""
    from pelican.readers import BaseReader
    from pelican.utils import pelican_open

    class _CommonMarkReader(BaseReader):
        """Markdown files as CommonMark with YAML front matter. Metadata
        goes through pelican's own processors; FORMATTED_FIELDS are
        rendered as Markdown."""
        enabled = True
        file_extensions = ["md", "markdown", "mkd", "mdown"]

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self._md = _make_md()

        def read(self, source_path):
            with pelican_open(source_path) as text:
                front, body = _split_front_matter(text)
            metadata = {}
            for name, value in (_yaml.safe_load(front) or {}).items():
                if value is None:
                    continue
                name = name.lower()
                if isinstance(value, (list, tuple)):
                    # tag and author slugs hold no comma, so pelican's
                    # comma split reads the list back exactly
                    value = ", ".join(str(item) for item in value)
                value = str(value)
                if name in self.settings["FORMATTED_FIELDS"]:
                    value = self._md.render(value)
                metadata[name] = self.process_metadata(name, value)
            return self._md.render(body), metadata

    return _CommonMarkReader


def _use_reader(readers):
    """Registers the CommonMark reader for every Markdown extension.
    Must stay at module level: pelican's signals hold receivers weakly,
    so a nested function would be garbage-collected and the reader
    silently never registered."""
    reader = _reader_class()
    for ext in reader.file_extensions:
        readers.reader_classes[ext] = reader


class _CommonMarkPlugin:
    @staticmethod
    def register():
        from pelican import signals

        signals.readers_init.connect(_use_reader)


# `{year}` in the footer is the build year
INTRO = _make_md().render(_INTRO_MD) if _INTRO_MD else None
FOOTER = (_make_md().render(
    _FOOTER_MD.replace("{year}", _datetime.date.today().strftime("%Y")))
    if _FOOTER_MD else None)
