// Generated by `medium-archive myst`; do not edit.
//
// Companion transform for the myst-listing plugin; load it after that
// plugin in myst.yml (transforms run in listing order). The gallery
// display renders each item's `thumbnail` as a CSS background-image,
// passing the front-matter string through verbatim, which only works for
// absolute URLs: nothing serves the source tree, and mystmd's image
// pipeline never looks inside CSS backgrounds. This transform rewrites
// each gallery card's cover into a real image node with a page-relative
// path, so mystmd copies the file into the build and rewrites the URL
// like any post body image.
import { posix, relative, sep } from "node:path";

const BG_URL = /^url\("([^"]+)"\)$/;

function isRelative(url) {
  return url && !/^[a-z][a-z0-9+.-]*:/i.test(url) && !url.startsWith("/");
}

function fixCovers(node, cardUrl, pageDir) {
  if (Array.isArray(node)) {
    for (const child of node) fixCovers(child, cardUrl, pageDir);
    return;
  }
  if (!node || typeof node !== "object") return;
  // gallery cards carry the item's project-rooted source path ("/posts/...")
  if (node.type === "card" && typeof node.url === "string") cardUrl = node.url;
  const bg = BG_URL.exec(node.style?.backgroundImage ?? "");
  if (node.type === "div" && /myst-listing-cover/.test(node.class ?? "") &&
      bg && isRelative(bg[1]) && cardUrl?.startsWith("/")) {
    // thumbnail is relative to the collected post file; rebase it onto the
    // card's source path, then express it relative to the listing page,
    // whose directory is what mystmd resolves image nodes against.
    const fromRoot = posix.join(posix.dirname(cardUrl.slice(1)), bg[1]);
    node.type = "image";
    node.url = posix.relative(pageDir, fromRoot) || fromRoot;
    node.alt = "";
    delete node.style;
    delete node.children;
    return;
  }
  fixCovers(node.children, cardUrl, pageDir);
}

const coverTransform = {
  name: "listing-cover-images",
  doc: "Turn relative myst-listing cover backgrounds into image nodes.",
  stage: "document",
  plugin: () => (tree, vfile) => {
    const pageDir = posix.dirname(
      relative(process.cwd(), vfile.path).split(sep).join("/"));
    fixCovers(tree.children, null, pageDir === "." ? "" : pageDir);
  },
};

const plugin = { name: "Listing cover images", transforms: [coverTransform] };
export default plugin;
